export type PersonRole = 'titolare' | 'dipendente';

export type WeekdayKey =
  | 'lunedi'
  | 'martedi'
  | 'mercoledi'
  | 'giovedi'
  | 'venerdi'
  | 'sabato'
  | 'domenica';

export const WEEKDAY_OPTIONS: Array<{ key: WeekdayKey; label: string }> = [
  { key: 'lunedi', label: 'Lunedi' },
  { key: 'martedi', label: 'Martedi' },
  { key: 'mercoledi', label: 'Mercoledi' },
  { key: 'giovedi', label: 'Giovedi' },
  { key: 'venerdi', label: 'Venerdi' },
  { key: 'sabato', label: 'Sabato' },
  { key: 'domenica', label: 'Domenica' },
];

export interface WeeklyShiftDay {
  isWorking: boolean;
  hours: number;
}

export type WeeklyShiftTemplate = Record<WeekdayKey, WeeklyShiftDay>;

export interface AppSettings {
  companyClosureDays: WeekdayKey[];
}

export function createWeeklyShiftTemplate(defaultDailyHours = 8): WeeklyShiftTemplate {
  return {
    lunedi: { isWorking: true, hours: defaultDailyHours },
    martedi: { isWorking: true, hours: defaultDailyHours },
    mercoledi: { isWorking: true, hours: defaultDailyHours },
    giovedi: { isWorking: true, hours: defaultDailyHours },
    venerdi: { isWorking: true, hours: defaultDailyHours },
    sabato: { isWorking: true, hours: defaultDailyHours },
    domenica: { isWorking: false, hours: 0 },
  };
}

export interface StaffMember {
  id: string;
  fullName: string;
  role: PersonRole;
  isActive: boolean;
  defaultDailyHours: number;
  weeklySchedule: WeeklyShiftTemplate;
  createdAt: string;
}

export interface DailySale {
  id: string;
  saleDate: string;
  staffMemberId: string;
  regularAmount: number;
  testAmount: number;
  notes: string;
  createdAt: string;
}

export type AttendanceType = 'lavoro' | 'festivo' | 'ferie' | 'permesso' | 'malattia';

export interface AttendanceEntry {
  id: string;
  staffMemberId: string;
  entryDate: string;
  entryType: AttendanceType;
  workedHours: number;
  notes: string;
  createdAt: string;
  isAutoGenerated?: boolean;
}

export interface StaffPerformance {
  staffMember: StaffMember;
  totalRegular: number;
  totalTest: number;
  totalAmount: number;
  daysWorked: number;
  averageDaily: number;
}

export interface AttendanceSummary {
  totalWorkedHours: number;
  workDays: number;
  holidayDays: number;
  vacationDays: number;
  permitDays: number;
  sickDays: number;
}
