import { CommonModule, CurrencyPipe, DatePipe, registerLocaleData } from '@angular/common';
import localeIt from '@angular/common/locales/it';
import { Component, computed, inject, OnDestroy, OnInit, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Session } from '@supabase/supabase-js';

import {
  AppSettings,
  AttendanceEntry,
  AttendanceSummary,
  AttendanceType,
  createWeeklyShiftTemplate,
  DailySale,
  PersonRole,
  StaffMember,
  StaffPerformance,
  WEEKDAY_OPTIONS,
  WeekdayKey,
  WeeklyShiftTemplate,
} from './models/store.models';
import { StoreService } from './services/store.service';

registerLocaleData(localeIt);

type AppSection = 'dashboard' | 'incasso' | 'report' | 'presenze' | 'impostazioni';
type AuthMode = 'sign-in' | 'sign-up';

type EffectiveAttendanceEntry = AttendanceEntry & { isAutoGenerated: boolean };
type AttendanceCalendarDay = {
  isoDate: string;
  dayNumber: number;
  weekdayLabel: string;
  isWeekend: boolean;
  weekdayKey: WeekdayKey;
  isCompanyClosed: boolean;
  isNationalHoliday: boolean;
  plannedShift: { isWorking: boolean; hours: number } | null;
  entry: EffectiveAttendanceEntry | null;
};
type StaffAttendanceMonthRow = {
  staffMember: StaffMember;
  summary: AttendanceSummary;
};

@Component({
  selector: 'app-root',
  imports: [CommonModule, FormsModule, CurrencyPipe, DatePipe],
  templateUrl: './app.html',
  styleUrl: './app.scss',
})
export class App implements OnInit, OnDestroy {
  private readonly storeService = inject(StoreService);
  private feedbackTimeoutId: ReturnType<typeof window.setTimeout> | null = null;
  private readonly attendanceEditWindowDays = 3;
  private authSubscription: { unsubscribe: () => void } | null = null;
  private loadedUserId: string | null = null;
  private loadingUserId: string | null = null;
  private readonly currentDateTimerId = window.setInterval(() => {
    this.currentDate.set(this.toInputDate(new Date()));
  }, 60_000);

  protected readonly title = 'Goldfinger Manager';
  protected readonly locale = 'it-IT';
  protected readonly currencyCode = 'EUR';
  protected readonly currentDate = signal(this.toInputDate(new Date()));
  protected readonly today = this.currentDate.asReadonly();
  protected readonly authSession = signal<Session | null>(null);
  protected readonly isAuthReady = signal(false);
  protected readonly isAuthProcessing = signal(false);
  protected readonly authMode = signal<AuthMode>('sign-in');
  protected readonly currentSection = signal<AppSection>('dashboard');
  protected readonly isSidebarOpen = signal(false);
  protected readonly feedback = signal<{ type: 'success' | 'error' | 'info'; message: string } | null>(
    null,
  );
  protected readonly isLoading = signal(true);
  protected readonly isSavingStaff = signal(false);
  protected readonly isSavingSale = signal(false);
  protected readonly isSavingAttendance = signal(false);
  protected readonly isSavingSettings = signal(false);
  protected readonly isAttendanceModalOpen = signal(false);
  protected readonly attendanceFilterVersion = signal(0);
  protected readonly appSettings = signal<AppSettings>({ companyClosureDays: ['domenica'] });
  protected readonly staffMembers = signal<StaffMember[]>([]);
  protected readonly dailySales = signal<DailySale[]>([]);
  protected readonly attendanceEntries = signal<AttendanceEntry[]>([]);
  protected readonly editingStaffMemberId = signal<string | null>(null);
  protected readonly menuItems: Array<{ id: AppSection; label: string }> = [
    { id: 'dashboard', label: 'Dashboard' },
    { id: 'incasso', label: 'Incasso' },
    { id: 'report', label: 'Report' },
    { id: 'presenze', label: 'Presenze' },
    { id: 'impostazioni', label: 'Impostazioni' },
  ];
  protected readonly weekdayOptions = WEEKDAY_OPTIONS;
  protected readonly authForm = {
    email: '',
    password: '',
    confirmPassword: '',
  };

  protected readonly staffForm = {
    fullName: '',
    role: 'dipendente' as PersonRole,
    defaultDailyHours: 8,
    weeklySchedule: createWeeklyShiftTemplate(8),
  };

  protected readonly saleForm = {
    saleDate: this.today(),
    staffMemberId: '',
    regularAmount: 0,
    testAmount: 0,
    notes: '',
  };

  protected readonly reportFilter = {
    month: this.today().slice(5, 7),
    year: String(new Date().getFullYear()),
  };
  protected readonly reportMonthOptions = [
    { value: '01', label: 'Gennaio' },
    { value: '02', label: 'Febbraio' },
    { value: '03', label: 'Marzo' },
    { value: '04', label: 'Aprile' },
    { value: '05', label: 'Maggio' },
    { value: '06', label: 'Giugno' },
    { value: '07', label: 'Luglio' },
    { value: '08', label: 'Agosto' },
    { value: '09', label: 'Settembre' },
    { value: '10', label: 'Ottobre' },
    { value: '11', label: 'Novembre' },
    { value: '12', label: 'Dicembre' },
  ];
  protected readonly attendanceTypeOptions: Array<{ value: AttendanceType; label: string }> = [
    { value: 'lavoro', label: 'Lavoro' },
    { value: 'festivo', label: 'Festivo' },
    { value: 'ferie', label: 'Ferie' },
    { value: 'permesso', label: 'Permesso' },
    { value: 'malattia', label: 'Malattia' },
  ];
  protected readonly attendanceForm = {
    staffMemberId: '',
    entryDate: this.today(),
    endDate: this.today(),
    entryType: 'lavoro' as AttendanceType,
    workedHours: 8,
    notes: '',
  };
  protected readonly editingAttendanceEntryId = signal<string | null>(null);
  protected readonly attendanceFilter = {
    month: this.today().slice(5, 7),
    year: String(new Date().getFullYear()),
    staffMemberId: '',
  };

  protected readonly currentSectionLabel = computed(() =>
    this.menuItems.find((item) => item.id === this.currentSection())?.label ?? 'Dashboard',
  );
  protected readonly isAuthenticated = computed(() => !!this.authSession());
  protected readonly currentUserEmail = computed(() => this.authSession()?.user.email ?? '');

  protected readonly staffMemberMap = computed(
    () => new Map(this.staffMembers().map((member) => [member.id, member])),
  );

  protected readonly activeStaffMembers = computed(() =>
    this.staffMembers().filter((member) => member.isActive),
  );

  protected readonly hiddenStaffMembers = computed(() =>
    this.staffMembers().filter((member) => !member.isActive),
  );

  protected readonly employeeStaffMembers = computed(() =>
    this.staffMembers().filter((member) => member.role === 'dipendente'),
  );

  protected readonly activeEmployeeStaffMembers = computed(() =>
    this.activeStaffMembers().filter((member) => member.role === 'dipendente'),
  );

  protected readonly orderedSales = computed(() =>
    [...this.dailySales()].sort((left, right) => {
      const dateComparison = right.saleDate.localeCompare(left.saleDate);

      if (dateComparison !== 0) {
        return dateComparison;
      }

      return right.createdAt.localeCompare(left.createdAt);
    }),
  );

  protected readonly filteredReportSales = computed(() =>
    this.filterSalesByMonth(this.orderedSales(), this.reportFilter.month, this.reportFilter.year),
  );

  protected readonly filteredReportTotal = computed(() =>
    this.filteredReportSales().reduce((total, sale) => total + sale.regularAmount + sale.testAmount, 0),
  );

  protected readonly totalRegular = computed(() =>
    this.dailySales().reduce((total, sale) => total + sale.regularAmount, 0),
  );

  protected readonly totalTest = computed(() =>
    this.dailySales().reduce((total, sale) => total + sale.testAmount, 0),
  );

  protected readonly totalAmount = computed(() => this.totalRegular() + this.totalTest());

  protected readonly todayTotal = computed(() =>
    this.dailySales()
      .filter((sale) => sale.saleDate === this.today())
      .reduce((total, sale) => total + sale.regularAmount + sale.testAmount, 0),
  );

  protected readonly currentMonthTotal = computed(() =>
    this.dailySales()
      .filter((sale) => sale.saleDate.startsWith(this.today().slice(0, 7)))
      .reduce((total, sale) => total + sale.regularAmount + sale.testAmount, 0),
  );

  protected readonly currentMonthLabel = computed(() =>
    new Intl.DateTimeFormat(this.locale, { month: 'long', year: 'numeric' }).format(new Date()),
  );

  protected readonly recentSales = computed(() => this.orderedSales().slice(0, 5));

  protected readonly availableReportYears = computed(() => {
    const currentYear = new Date().getFullYear();
    const saleYears = this.dailySales().map((sale) => Number.parseInt(sale.saleDate.slice(0, 4), 10));
    const earliestYear = saleYears.length ? Math.min(...saleYears) : currentYear;
    const years: string[] = [];

    for (let year = currentYear; year >= earliestYear; year -= 1) {
      years.push(String(year));
    }

    return years;
  });

  protected readonly availableAttendanceYears = computed(() => {
    const currentYear = new Date().getFullYear();
    const attendanceYears = this.attendanceEntries().map((entry) => Number.parseInt(entry.entryDate.slice(0, 4), 10));
    const earliestYear = attendanceYears.length ? Math.min(...attendanceYears) : currentYear;
    const years: string[] = [];

    for (let year = currentYear; year >= earliestYear; year -= 1) {
      years.push(String(year));
    }

    return years;
  });

  protected readonly reportPeriodLabel = computed(() => {
    const monthLabel =
      this.reportMonthOptions.find((month) => month.value === this.reportFilter.month)?.label ?? 'Mese';
    return `${monthLabel} ${this.reportFilter.year}`;
  });

  protected readonly attendancePeriodLabel = computed(() => {
    const monthLabel =
      this.reportMonthOptions.find((month) => month.value === this.attendanceFilter.month)?.label ?? 'Mese';
    return `${monthLabel} ${this.attendanceFilter.year}`;
  });

  protected readonly reportRows = computed<StaffPerformance[]>(() => {
    const salesByStaffMember = new Map<string, DailySale[]>();

    for (const sale of this.filteredReportSales()) {
      const collection = salesByStaffMember.get(sale.staffMemberId) ?? [];
      collection.push(sale);
      salesByStaffMember.set(sale.staffMemberId, collection);
    }

    return this.staffMembers()
      .map((staffMember) => {
        const sales = salesByStaffMember.get(staffMember.id) ?? [];
        const totalRegular = sales.reduce((total, sale) => total + sale.regularAmount, 0);
        const totalTest = sales.reduce((total, sale) => total + sale.testAmount, 0);
        const workedDays = new Set(sales.map((sale) => sale.saleDate)).size;
        const totalAmount = totalRegular + totalTest;

        return {
          staffMember,
          totalRegular,
          totalTest,
          totalAmount,
          daysWorked: workedDays,
          averageDaily: workedDays > 0 ? totalAmount / workedDays : 0,
        };
      })
      .filter((row) => row.staffMember.isActive || row.totalAmount > 0)
      .sort((left, right) => right.totalAmount - left.totalAmount);
  });

  protected readonly reportMaxTotal = computed(() =>
    this.reportRows().reduce((maxValue, row) => Math.max(maxValue, row.totalAmount), 0),
  );

  protected readonly monthlySales = computed(() => this.filteredReportSales());

  protected readonly filteredAttendanceEntries = computed(() =>
    (this.attendanceFilterVersion(),
    this.filterAttendanceByMonth(this.attendanceEntries(), this.attendanceFilter.month, this.attendanceFilter.year)),
  );

  protected readonly explicitAttendanceEntriesForSelectedStaff = computed(() =>
    this.filteredAttendanceEntries().filter((entry) => entry.staffMemberId === this.attendanceFilter.staffMemberId),
  );

  protected readonly attendanceEntriesForSelectedStaff = computed<EffectiveAttendanceEntry[]>(() =>
    this.buildMonthlyAttendanceEntries(this.attendanceFilter.staffMemberId),
  );

  protected readonly attendanceSummary = computed<AttendanceSummary>(() =>
    this.buildAttendanceSummary(this.attendanceEntriesForSelectedStaff()),
  );

  protected readonly attendanceSummaryByStaff = computed<StaffAttendanceMonthRow[]>(() =>
    this.employeeStaffMembers()
      .map((staffMember) => ({
        staffMember,
        summary: this.buildAttendanceSummary(this.buildMonthlyAttendanceEntries(staffMember.id)),
      }))
      .filter((row) => row.staffMember.isActive || row.summary.totalWorkedHours > 0 || row.summary.vacationDays > 0 || row.summary.permitDays > 0 || row.summary.sickDays > 0)
      .sort((left, right) => left.staffMember.fullName.localeCompare(right.staffMember.fullName)),
  );

  protected readonly attendanceCalendarDays = computed(() => {
    this.attendanceFilterVersion();
    const year = Number.parseInt(this.attendanceFilter.year, 10);
    const monthIndex = Number.parseInt(this.attendanceFilter.month, 10) - 1;
    const firstDay = new Date(year, monthIndex, 1);
    const lastDay = new Date(year, monthIndex + 1, 0);
    const days: AttendanceCalendarDay[] = [];
    const selectedStaffMember = this.getAttendanceStaffMemberById(this.attendanceFilter.staffMemberId);

    for (let day = 1; day <= lastDay.getDate(); day += 1) {
      const currentDate = new Date(year, monthIndex, day);
      const isoDate = this.toInputDate(currentDate);
      const weekdayKey = this.getWeekdayKeyFromDate(isoDate);
      const plannedShift = selectedStaffMember ? this.getPlannedShiftForDate(selectedStaffMember, isoDate) : null;
      const isNationalHoliday = this.isNationalHolidayDate(isoDate);
      days.push({
        isoDate,
        dayNumber: day,
        weekdayLabel: new Intl.DateTimeFormat(this.locale, { weekday: 'short' }).format(currentDate),
        isWeekend: weekdayKey === 'sabato' || weekdayKey === 'domenica',
        entry:
          this.attendanceEntriesForSelectedStaff().find((entry) => entry.entryDate === isoDate) ?? null,
        weekdayKey,
        isCompanyClosed: this.isCompanyClosureDate(isoDate),
        isNationalHoliday,
        plannedShift,
      });
    }

    return {
      monthStartWeekday: (firstDay.getDay() + 6) % 7,
      days,
    };
  });

  ngOnInit(): void {
    void this.initializeApp();
  }

  ngOnDestroy(): void {
    window.clearInterval(this.currentDateTimerId);

    if (this.feedbackTimeoutId) {
      window.clearTimeout(this.feedbackTimeoutId);
    }

    this.authSubscription?.unsubscribe();
  }

  protected setAuthMode(mode: AuthMode): void {
    this.authMode.set(mode);
    this.authForm.password = '';
    this.authForm.confirmPassword = '';
  }

  protected async submitAuth(): Promise<void> {
    const email = this.authForm.email.trim().toLowerCase();
    const password = this.authForm.password;
    const confirmPassword = this.authForm.confirmPassword;

    if (!email) {
      this.setFeedback('error', 'Inserisci l\'email.');
      return;
    }

    if (!password) {
      this.setFeedback('error', 'Inserisci la password.');
      return;
    }

    if (this.authMode() === 'sign-up' && password !== confirmPassword) {
      this.setFeedback('error', 'Password e conferma password non coincidono.');
      return;
    }

    this.isAuthProcessing.set(true);

    try {
      if (this.authMode() === 'sign-up') {
        const result = await this.storeService.signUp(email, password);

        if (result.needsEmailConfirmation) {
          this.authForm.password = '';
          this.authForm.confirmPassword = '';
          this.authMode.set('sign-in');
          this.setFeedback('info', 'Account creato. Conferma l\'email e poi accedi.');
          return;
        }

        this.setFeedback('success', 'Account creato e accesso effettuato.');
        return;
      }

      await this.storeService.signIn(email, password);
      this.authForm.password = '';
      this.authForm.confirmPassword = '';
      this.setFeedback('success', 'Accesso effettuato.');
    } catch (error) {
      this.setFeedback('error', this.getErrorMessage(error, 'Impossibile completare l\'accesso.'));
    } finally {
      this.isAuthProcessing.set(false);
    }
  }

  protected async logout(): Promise<void> {
    this.isAuthProcessing.set(true);

    try {
      await this.storeService.signOut();
      this.setFeedback('info', 'Logout effettuato.');
    } catch (error) {
      this.setFeedback('error', this.getErrorMessage(error, 'Impossibile completare il logout.'));
    } finally {
      this.isAuthProcessing.set(false);
    }
  }

  protected toggleSidebar(): void {
    this.isSidebarOpen.update((value) => !value);
  }

  protected closeSidebar(): void {
    this.isSidebarOpen.set(false);
  }

  protected openSection(section: AppSection): void {
    this.currentSection.set(section);
    this.closeSidebar();
  }

  protected async saveStaffMember(): Promise<void> {
    const fullName = this.staffForm.fullName.trim();
    const defaultDailyHours = this.normalizeAmount(this.staffForm.defaultDailyHours);
    const weeklySchedule = this.normalizeWeeklyScheduleForm(this.staffForm.weeklySchedule);

    if (!fullName) {
      this.setFeedback('error', 'Inserisci il nome della persona da registrare.');
      return;
    }

    if (defaultDailyHours < 0) {
      this.setFeedback('error', 'Le ore giornaliere non possono essere negative.');
      return;
    }

    const weeklyScheduleError = this.getWeeklyScheduleValidationError(weeklySchedule);

    if (weeklyScheduleError) {
      this.setFeedback('error', weeklyScheduleError);
      return;
    }

    const duplicateMember = this.staffMembers().find(
      (member) =>
        member.id !== this.editingStaffMemberId() && member.fullName.toLowerCase() === fullName.toLowerCase(),
    );

    if (duplicateMember) {
      this.setFeedback('error', 'Esiste gia un membro del personale con questo nome.');
      return;
    }

    if (
      this.staffForm.role === 'titolare' &&
      this.ownerCount(this.editingStaffMemberId()) >= 1
    ) {
      this.setFeedback('error', 'Puoi registrare una sola titolare.');
      return;
    }

    if (
      this.staffForm.role === 'dipendente' &&
      this.employeeCount(this.editingStaffMemberId()) >= 2
    ) {
      this.setFeedback('error', 'Hai indicato un massimo di due dipendenti.');
      return;
    }

    this.isSavingStaff.set(true);

    try {
      const editingStaffMemberId = this.editingStaffMemberId();

      if (editingStaffMemberId) {
        await this.storeService.updateStaffMemberSettings({
          staffMemberId: editingStaffMemberId,
          fullName,
          role: this.staffForm.role,
          defaultDailyHours,
          weeklySchedule,
        });
        this.staffMembers.update((members) =>
          members.map((member) =>
            member.id === editingStaffMemberId
              ? { ...member, fullName, role: this.staffForm.role, defaultDailyHours, weeklySchedule }
              : member,
          ),
        );
        this.setFeedback('success', 'Personale aggiornato correttamente.');
      } else {
        const createdStaffMember = await this.storeService.createStaffMember(
          fullName,
          this.staffForm.role,
          defaultDailyHours,
          weeklySchedule,
        );
        this.staffMembers.update((members) => [...members, createdStaffMember]);

        if (!this.saleForm.staffMemberId) {
          this.saleForm.staffMemberId = createdStaffMember.id;
        }

        if (!this.attendanceForm.staffMemberId && createdStaffMember.role === 'dipendente' && createdStaffMember.isActive) {
          this.attendanceForm.staffMemberId = createdStaffMember.id;
        }

        this.setFeedback('success', 'Personale registrato correttamente.');
      }

      this.resetStaffForm();
      this.ensureSelectedStaffMember();
      this.ensureSelectedAttendanceStaffMember();
    } finally {
      this.isSavingStaff.set(false);
    }
  }

  protected startEditStaffMember(staffMember: StaffMember): void {
    this.editingStaffMemberId.set(staffMember.id);
    this.staffForm.fullName = staffMember.fullName;
    this.staffForm.role = staffMember.role;
    this.staffForm.defaultDailyHours = staffMember.defaultDailyHours;
    this.staffForm.weeklySchedule = this.cloneWeeklySchedule(staffMember.weeklySchedule);
    this.currentSection.set('impostazioni');
  }

  protected cancelStaffEdit(): void {
    this.resetStaffForm();
  }

  protected async saveCompanySettings(): Promise<void> {
    this.isSavingSettings.set(true);

    try {
      await this.storeService.updateAppSettings(this.appSettings());
      this.staffMembers.update((members) =>
        members.map((member) => ({
          ...member,
          weeklySchedule: this.normalizeWeeklyScheduleForm(member.weeklySchedule),
        })),
      );
      this.setFeedback('success', 'Chiusure aziendali aggiornate.');
    } finally {
      this.isSavingSettings.set(false);
    }
  }

  protected toggleCompanyClosureDay(day: WeekdayKey): void {
    this.appSettings.update((settings) => {
      const daySet = new Set(settings.companyClosureDays);

      if (daySet.has(day)) {
        daySet.delete(day);
      } else {
        daySet.add(day);
      }

      return {
        companyClosureDays: [...daySet],
      };
    });

    this.staffForm.weeklySchedule = this.normalizeWeeklyScheduleForm(this.staffForm.weeklySchedule);
  }

  protected isCompanyClosureDay(day: WeekdayKey): boolean {
    return this.appSettings().companyClosureDays.includes(day);
  }

  protected toggleStaffWorkingDay(day: WeekdayKey): void {
    if (this.isCompanyClosureDay(day)) {
      return;
    }

    const currentDay = this.staffForm.weeklySchedule[day];
    this.staffForm.weeklySchedule = {
      ...this.staffForm.weeklySchedule,
      [day]: {
        isWorking: !currentDay.isWorking,
        hours: !currentDay.isWorking ? this.normalizeAmount(this.staffForm.defaultDailyHours) : 0,
      },
    };
  }

  protected updateStaffWorkingHours(day: WeekdayKey, hours: number): void {
    const normalizedHours = Math.max(0, this.normalizeAmount(hours));
    this.staffForm.weeklySchedule = {
      ...this.staffForm.weeklySchedule,
      [day]: {
        isWorking: !this.isCompanyClosureDay(day) && normalizedHours > 0,
        hours: this.isCompanyClosureDay(day) ? 0 : normalizedHours,
      },
    };
  }

  protected async hideOrDeleteStaffMember(staffMember: StaffMember): Promise<void> {
    if (this.hasStaffSales(staffMember.id)) {
      if (!window.confirm(`Nascondere ${staffMember.fullName}? Rimarra nei report storici ma non comparira piu in incasso.`)) {
        return;
      }

      await this.storeService.updateStaffMemberVisibility(staffMember.id, false);
      this.staffMembers.update((members) =>
        members.map((member) => (member.id === staffMember.id ? { ...member, isActive: false } : member)),
      );
      this.ensureSelectedStaffMember();
      this.setFeedback('info', 'Personale nascosto con successo.');
      return;
    }

    if (!window.confirm(`Eliminare ${staffMember.fullName}?`)) {
      return;
    }

    await this.storeService.deleteStaffMember(staffMember.id);
    this.staffMembers.update((members) => members.filter((member) => member.id !== staffMember.id));
    this.ensureSelectedStaffMember();
    this.setFeedback('info', 'Personale eliminato.');
  }

  protected async restoreStaffMember(staffMember: StaffMember): Promise<void> {
    if (staffMember.role === 'titolare' && this.ownerCount() >= 1) {
      this.setFeedback('error', 'Hai gia una titolare attiva.');
      return;
    }

    if (staffMember.role === 'dipendente' && this.employeeCount() >= 2) {
      this.setFeedback('error', 'Hai gia due dipendenti attivi.');
      return;
    }

    await this.storeService.updateStaffMemberVisibility(staffMember.id, true);
    this.staffMembers.update((members) =>
      members.map((member) => (member.id === staffMember.id ? { ...member, isActive: true } : member)),
    );
    this.ensureSelectedStaffMember();
    this.setFeedback('success', 'Personale riattivato.');
  }

  protected async addDailySale(): Promise<void> {
    if (!this.saleForm.staffMemberId) {
      this.setFeedback('error', 'Seleziona prima la titolare o una dipendente.');
      return;
    }

    if (!this.saleForm.saleDate) {
      this.setFeedback('error', 'Inserisci la data dell\'incasso.');
      return;
    }

    if (this.saleForm.regularAmount <= 0 && this.saleForm.testAmount <= 0) {
      this.setFeedback('error', 'Inserisci almeno un importo maggiore di zero.');
      return;
    }

    this.isSavingSale.set(true);

    try {
      const createdSale = await this.storeService.createDailySale({
        saleDate: this.saleForm.saleDate,
        staffMemberId: this.saleForm.staffMemberId,
        regularAmount: this.normalizeAmount(this.saleForm.regularAmount),
        testAmount: this.normalizeAmount(this.saleForm.testAmount),
        notes: this.saleForm.notes,
      });

      this.dailySales.update((sales) => [...sales, createdSale]);
      this.saleForm.regularAmount = 0;
      this.saleForm.testAmount = 0;
      this.saleForm.notes = '';
      this.setFeedback('success', 'Incasso giornaliero salvato.');
    } finally {
      this.isSavingSale.set(false);
    }
  }

  protected onAttendanceStaffChange(): void {
    const selectedStaffMember = this.staffMemberMap().get(this.attendanceForm.staffMemberId);

    if (!selectedStaffMember) {
      return;
    }

    const plannedShift = this.getPlannedShiftForDate(selectedStaffMember, this.attendanceForm.entryDate);
    this.attendanceForm.workedHours = plannedShift?.hours ?? 0;
  }

  protected selectAttendanceDay(isoDate: string): void {
    if (this.attendanceFilter.staffMemberId) {
      this.attendanceForm.staffMemberId = this.attendanceFilter.staffMemberId;
    }

    this.attendanceForm.entryDate = isoDate;
    this.attendanceForm.endDate = isoDate;

    const existingEntry = this.explicitAttendanceEntriesForSelectedStaff().find((entry) => entry.entryDate === isoDate);

    if (existingEntry) {
      this.startEditAttendanceEntry(existingEntry);
      this.isAttendanceModalOpen.set(true);
      return;
    }

    this.editingAttendanceEntryId.set(null);
    const selectedStaffMember = this.getSelectedAttendanceStaffMember();
    const plannedShift = selectedStaffMember ? this.getPlannedShiftForDate(selectedStaffMember, isoDate) : null;
    this.attendanceForm.entryType = !plannedShift || !plannedShift.isWorking ? 'festivo' : 'lavoro';
    this.attendanceForm.notes = '';
    this.attendanceForm.workedHours = plannedShift?.hours ?? 0;
    this.isAttendanceModalOpen.set(true);
  }

  protected onAttendanceFilterStaffChange(): void {
    this.attendanceFilterVersion.update((value) => value + 1);

    if (!this.attendanceFilter.staffMemberId) {
      return;
    }

    this.attendanceForm.staffMemberId = this.attendanceFilter.staffMemberId;
    this.resetAttendanceForm();
  }

  protected onAttendanceFilterPeriodChange(): void {
    this.attendanceFilterVersion.update((value) => value + 1);
    this.closeAttendanceModal();
  }

  protected closeAttendanceModal(): void {
    this.isAttendanceModalOpen.set(false);
  }

  protected onAttendanceTypeChange(): void {
    const selectedStaffMember = this.staffMemberMap().get(this.attendanceForm.staffMemberId);

    if (!selectedStaffMember) {
      return;
    }

    if (this.attendanceForm.entryType === 'lavoro') {
      const plannedShift = this.getPlannedShiftForDate(selectedStaffMember, this.attendanceForm.entryDate);
      this.attendanceForm.workedHours = plannedShift?.hours ?? selectedStaffMember.defaultDailyHours;
      return;
    }

    if (this.attendanceForm.entryType === 'festivo') {
      this.attendanceForm.workedHours = 0;
      return;
    }

    if (this.attendanceForm.entryType === 'ferie' || this.attendanceForm.entryType === 'malattia') {
      this.attendanceForm.workedHours = 0;
      this.attendanceForm.endDate = this.attendanceForm.entryDate;
      return;
    }

    const plannedShift = this.getPlannedShiftForDate(selectedStaffMember, this.attendanceForm.entryDate);
    this.attendanceForm.workedHours = plannedShift?.hours ?? selectedStaffMember.defaultDailyHours;
  }

  protected async addAttendanceEntry(): Promise<void> {
    if (!this.attendanceForm.staffMemberId) {
      this.setFeedback('error', 'Seleziona un dipendente per registrare la presenza.');
      return;
    }

    if (!this.attendanceForm.entryDate) {
      this.setFeedback('error', 'Inserisci la data della presenza.');
      return;
    }

    if (this.attendanceForm.workedHours < 0) {
      this.setFeedback('error', 'Le ore non possono essere negative.');
      return;
    }

    if (this.attendanceForm.endDate < this.attendanceForm.entryDate) {
      this.setFeedback('error', 'La data finale non puo essere precedente alla data iniziale.');
      return;
    }

    if (this.attendanceForm.entryType === 'festivo' && this.attendanceForm.workedHours !== 0) {
      this.setFeedback('error', 'Per i giorni festivi le ore devono essere pari a zero.');
      return;
    }

    if (this.attendanceForm.entryType === 'lavoro' && this.attendanceForm.workedHours <= 0) {
      this.setFeedback('error', 'Per un giorno lavorativo inserisci ore maggiori di zero.');
      return;
    }

    const selectedStaffMember = this.getSelectedAttendanceStaffMember();

    if (!selectedStaffMember) {
      this.setFeedback('error', 'Seleziona un dipendente valido.');
      return;
    }

    const plannedShift = this.getPlannedShiftForDate(selectedStaffMember, this.attendanceForm.entryDate);

    if (this.attendanceForm.entryType === 'lavoro' && (!plannedShift || !plannedShift.isWorking)) {
      this.setFeedback('error', 'Non puoi inserire un turno lavorativo in un giorno non lavorativo o di chiusura.');
      return;
    }

    if (
      this.attendanceForm.entryType === 'lavoro' &&
      plannedShift &&
      this.normalizeAmount(this.attendanceForm.workedHours) !== this.normalizeAmount(plannedShift.hours)
    ) {
      this.setFeedback('error', 'Le ore inserite devono coincidere con le ore effettive previste dal turno.');
      return;
    }

    this.isSavingAttendance.set(true);

    try {
      const normalizedHours = this.normalizeAmount(this.attendanceForm.workedHours);
      const isRangeEntry =
        this.attendanceForm.entryType === 'ferie' || this.attendanceForm.entryType === 'malattia';
      const targetDates = isRangeEntry
        ? this.getDateRange(this.attendanceForm.entryDate, this.attendanceForm.endDate)
        : [this.attendanceForm.entryDate];
      const conflictingEntry = this.findConflictingExplicitEntry(targetDates, this.editingAttendanceEntryId());

      if (conflictingEntry) {
        this.setFeedback('error', `Esiste gia una presenza registrata il ${this.formatDate(conflictingEntry.entryDate)}.`);
        return;
      }

      if (this.editingAttendanceEntryId()) {
        const attendanceEntryId = this.editingAttendanceEntryId();

        if (!attendanceEntryId) {
          return;
        }

        const currentEntry = this.attendanceEntries().find((entry) => entry.id === attendanceEntryId);

        if (!currentEntry || !this.canEditAttendanceEntry(currentEntry)) {
          this.setFeedback('error', 'La presenza non e piu modificabile.');
          return;
        }

        await this.storeService.updateAttendanceEntry({
          attendanceEntryId,
          staffMemberId: this.attendanceForm.staffMemberId,
          entryDate: this.attendanceForm.entryDate,
          entryType: this.attendanceForm.entryType,
          workedHours: normalizedHours,
          notes: this.attendanceForm.notes,
        });

        this.attendanceEntries.update((entries) =>
          entries.map((entry) =>
            entry.id === attendanceEntryId
              ? {
                  ...entry,
                  staffMemberId: this.attendanceForm.staffMemberId,
                  entryDate: this.attendanceForm.entryDate,
                  entryType: this.attendanceForm.entryType,
                  workedHours: normalizedHours,
                  notes: this.attendanceForm.notes.trim(),
                }
              : entry,
          ),
        );
        this.setFeedback('success', 'Presenza aggiornata correttamente.');
      } else {
        const createdEntries: AttendanceEntry[] = [];

        for (const targetDate of targetDates) {
          const createdEntry = await this.storeService.createAttendanceEntry({
            staffMemberId: this.attendanceForm.staffMemberId,
            entryDate: targetDate,
            entryType: this.attendanceForm.entryType,
            workedHours:
              this.attendanceForm.entryType === 'permesso'
                ? normalizedHours
                : this.attendanceForm.entryType === 'lavoro'
                  ? normalizedHours
                  : 0,
            notes: this.attendanceForm.notes,
          });
          createdEntries.push(createdEntry);
        }

        this.attendanceEntries.update((entries) => [...entries, ...createdEntries]);
        this.attendanceFilter.staffMemberId = this.attendanceForm.staffMemberId;
        this.attendanceFilter.month = this.attendanceForm.entryDate.slice(5, 7);
        this.attendanceFilter.year = this.attendanceForm.entryDate.slice(0, 4);
        this.setFeedback(
          'success',
          isRangeEntry
            ? `${this.getAttendanceTypeLabel(this.attendanceForm.entryType)} registrata dal ${this.formatDate(this.attendanceForm.entryDate)} al ${this.formatDate(this.attendanceForm.endDate)}.`
            : 'Presenza registrata correttamente.',
        );
      }

      this.resetAttendanceForm();
      this.isAttendanceModalOpen.set(false);
    } finally {
      this.isSavingAttendance.set(false);
    }
  }

  protected startEditAttendanceEntry(entry: AttendanceEntry): void {
    this.editingAttendanceEntryId.set(entry.id);
    this.attendanceForm.staffMemberId = entry.staffMemberId;
    this.attendanceForm.entryDate = entry.entryDate;
    this.attendanceForm.endDate = entry.entryDate;
    this.attendanceForm.entryType = entry.entryType;
    this.attendanceForm.workedHours = entry.workedHours;
    this.attendanceForm.notes = entry.notes;
  }

  protected cancelAttendanceEdit(): void {
    this.resetAttendanceForm();
    this.isAttendanceModalOpen.set(false);
  }

  protected canEditAttendanceEntry(entry: AttendanceEntry): boolean {
    const today = new Date(this.today());
    const entryDate = new Date(entry.entryDate);
    const differenceMs = today.getTime() - entryDate.getTime();
    const differenceDays = differenceMs / (1000 * 60 * 60 * 24);
    return differenceDays <= this.attendanceEditWindowDays;
  }

  protected async deleteAttendanceEntry(entry: AttendanceEntry): Promise<void> {
    if (!this.canEditAttendanceEntry(entry)) {
      this.setFeedback('error', 'La presenza non puo piu essere corretta o eliminata.');
      return;
    }

    if (!window.confirm('Eliminare questa presenza?')) {
      return;
    }

    await this.storeService.deleteAttendanceEntry(entry.id);
    this.attendanceEntries.update((entries) => entries.filter((currentEntry) => currentEntry.id !== entry.id));
    this.setFeedback('info', 'Presenza eliminata.');
    this.isAttendanceModalOpen.set(false);
  }

  protected async deleteDailySale(sale: DailySale): Promise<void> {
    if (!window.confirm('Eliminare questo incasso giornaliero?')) {
      return;
    }

    await this.storeService.deleteDailySale(sale.id);
    this.dailySales.update((sales) => sales.filter((currentSale) => currentSale.id !== sale.id));
    this.setFeedback('info', 'Incasso eliminato.');
  }

  protected async exportPdf(staffMember?: StaffMember): Promise<void> {
    const sales = staffMember
      ? this.getSalesForStaffInCurrentReport(staffMember.id)
      : this.filteredReportSales();

    if (sales.length === 0) {
      this.setFeedback('error', 'Non ci sono incassi nel periodo selezionato per generare il PDF.');
      return;
    }

    const [{ default: jsPDF }, { default: autoTable }] = await Promise.all([
      import('jspdf'),
      import('jspdf-autotable'),
    ]);

    const document = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4',
    });

    document.setFontSize(18);
    document.text(
      staffMember ? `Report ${staffMember.fullName}` : 'Report incassi Goldfinger Manager',
      14,
      18,
    );
    document.setFontSize(11);
    document.text(`Mese: ${this.reportPeriodLabel()}`, 14, 26);

    autoTable(document, {
      startY: 34,
      head: [['Data', 'Persona', 'Regolare', 'Test', 'Totale', 'Note']],
      body: sales.map((sale) => [
        this.formatDate(sale.saleDate),
        this.staffMemberMap().get(sale.staffMemberId)?.fullName ?? 'Non assegnato',
        this.formatCurrency(sale.regularAmount),
        this.formatCurrency(sale.testAmount),
        this.formatCurrency(sale.regularAmount + sale.testAmount),
        sale.notes || '-',
      ]),
      styles: {
        fontSize: 9,
        cellPadding: 2,
      },
      headStyles: {
        fillColor: [31, 41, 55],
      },
    });

    const totals = sales.reduce(
      (accumulator, sale) => {
        accumulator.regular += sale.regularAmount;
        accumulator.test += sale.testAmount;
        return accumulator;
      },
      { regular: 0, test: 0 },
    );

    const finalY = (document as typeof document & { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY ?? 34;
    document.setFontSize(11);
    document.text(`Totale regolare: ${this.formatCurrency(totals.regular)}`, 14, finalY + 12);
    document.text(`Totale test: ${this.formatCurrency(totals.test)}`, 14, finalY + 19);
    document.text(`Totale complessivo: ${this.formatCurrency(totals.regular + totals.test)}`, 14, finalY + 26);
    document.save(
      staffMember
        ? `report-incassi-${staffMember.fullName.toLowerCase().replaceAll(' ', '-')}-${this.reportFilter.year}-${this.reportFilter.month}.pdf`
        : `report-incassi-${this.reportFilter.year}-${this.reportFilter.month}.pdf`,
    );

    this.setFeedback(
      'success',
      staffMember ? `PDF generato per ${staffMember.fullName}.` : 'PDF generato correttamente.',
    );
  }

  protected async exportAttendancePdf(): Promise<void> {
    const rows = this.attendanceSummaryByStaff();

    if (rows.length === 0) {
      this.setFeedback('error', 'Non ci sono dipendenti da esportare nel mese selezionato.');
      return;
    }

    const year = Number.parseInt(this.attendanceFilter.year, 10);
    const monthIndex = Number.parseInt(this.attendanceFilter.month, 10) - 1;
    const daysInMonth = new Date(year, monthIndex + 1, 0).getDate();
    const dayHeaders = Array.from({ length: daysInMonth }, (_, index) => String(index + 1));
    const pageWidth = 297;
    const marginLeft = 8;
    const marginRight = 8;
    const availableTableWidth = pageWidth - marginLeft - marginRight;
    const staffColumnWidth = 56;
    const totalColumnWidth = 14;
    const dayCellWidth = Math.max(
      6.8,
      (availableTableWidth - staffColumnWidth - totalColumnWidth) / daysInMonth,
    );

    const [{ default: jsPDF }, { default: autoTable }] = await Promise.all([
      import('jspdf'),
      import('jspdf-autotable'),
    ]);

    const document = new jsPDF({
      orientation: 'landscape',
      unit: 'mm',
      format: 'a4',
    });

    document.setFontSize(18);
    document.text('Registro Presenze Mensile', 12, 14);
    document.setFontSize(12);
    document.text(`Periodo: ${this.attendancePeriodLabel()}`, 12, 22);
    document.text('Legenda: numero=ore lavorate/permesso, F=ferie, M=malattia, C=chiuso/festivo', 12, 29);

    const tableHead = [['Dipendente', ...dayHeaders, 'Tot']];
    const tableBody = rows.map(({ staffMember }) => {
      const entriesMap = new Map(
        this.buildMonthlyAttendanceEntries(staffMember.id).map((entry) => [entry.entryDate, entry]),
      );
      const dayCells: string[] = [];
      let workedHoursTotal = 0;

      for (let day = 1; day <= daysInMonth; day += 1) {
        const isoDate = this.toInputDate(new Date(year, monthIndex, day));
        const entry = entriesMap.get(isoDate);

        if (entry) {
          if (entry.entryType === 'ferie') {
            dayCells.push('F');
          } else if (entry.entryType === 'malattia') {
            dayCells.push('M');
          } else if (entry.entryType === 'festivo') {
            dayCells.push('C');
          } else {
            dayCells.push(this.formatCompactHours(entry.workedHours));
            workedHoursTotal += entry.workedHours;
          }
          continue;
        }

        if (this.isHolidayDate(isoDate)) {
          dayCells.push('C');
          continue;
        }

        dayCells.push('-');
      }

      return [staffMember.fullName, ...dayCells, this.formatCompactHours(workedHoursTotal)];
    });

    autoTable(document, {
      startY: 33,
      head: tableHead,
      body: tableBody,
      styles: {
        fontSize: 8.2,
        cellPadding: 1.6,
        halign: 'center',
        valign: 'middle',
        lineColor: [229, 231, 235],
        lineWidth: 0.1,
      },
      headStyles: {
        fillColor: [31, 41, 55],
        textColor: 255,
        fontSize: 8.5,
      },
      columnStyles: {
        0: { cellWidth: staffColumnWidth, halign: 'left' },
        [daysInMonth + 1]: { cellWidth: totalColumnWidth, halign: 'right' },
      },
      tableWidth: 'auto',
      margin: { left: marginLeft, right: marginRight },
      didParseCell: (hookData) => {
        if (hookData.column.index > 0 && hookData.column.index <= daysInMonth) {
          hookData.cell.styles.cellWidth = dayCellWidth;
        }
      },
    });

    document.save(
      `presenze-mensili-${this.attendanceFilter.year}-${this.attendanceFilter.month}.pdf`,
    );

    this.setFeedback('success', 'PDF mensile presenze generato correttamente.');
  }

  protected getStaffLabel(staffMemberId: string): string {
    return this.staffMemberMap().get(staffMemberId)?.fullName ?? 'Non assegnato';
  }

  protected getRoleLabel(role: PersonRole): string {
    return role === 'titolare' ? 'Titolare' : 'Dipendente';
  }

  protected getStaffActionLabel(staffMember: StaffMember): string {
    return this.hasStaffSales(staffMember.id) ? 'Nascondi' : 'Elimina';
  }

  protected hasStaffSales(staffMemberId: string): boolean {
    return this.dailySales().some((sale) => sale.staffMemberId === staffMemberId);
  }

  protected getBarWidth(totalAmount: number): string {
    const maxTotal = this.reportMaxTotal();

    if (!maxTotal) {
      return '0%';
    }

    return `${Math.max((totalAmount / maxTotal) * 100, 8)}%`;
  }

  protected trackByStaffMember(_: number, staffMember: StaffMember): string {
    return staffMember.id;
  }

  protected trackBySale(_: number, sale: DailySale): string {
    return sale.id;
  }

  protected trackByAttendance(_: number, entry: AttendanceEntry): string {
    return entry.id;
  }

  protected trackBySection(_: number, item: { id: AppSection }): string {
    return item.id;
  }

  private async initializeApp(): Promise<void> {
    this.authSubscription = this.storeService.onAuthStateChange((session) => {
      void this.syncAuthSession(session);
    });

    try {
      const session = await this.storeService.getSession();
      await this.syncAuthSession(session);
    } catch (error) {
      this.isLoading.set(false);
      this.isAuthReady.set(true);
      this.setFeedback('error', this.getErrorMessage(error, 'Impossibile avviare il login.'));
    }
  }

  private async syncAuthSession(session: Session | null): Promise<void> {
    this.authSession.set(session);
    this.isAuthReady.set(true);

    if (!session) {
      this.loadedUserId = null;
      this.loadingUserId = null;
      this.clearDataState();
      this.isLoading.set(false);
      return;
    }

    if (this.loadedUserId === session.user.id || this.loadingUserId === session.user.id) {
      return;
    }

    this.loadingUserId = session.user.id;

    try {
      await this.loadData();
      this.loadedUserId = session.user.id;
    } finally {
      if (this.loadingUserId === session.user.id) {
        this.loadingUserId = null;
      }
    }
  }

  private async loadData(): Promise<void> {
    this.isLoading.set(true);

    try {
      const [appSettings, staffMembers, dailySales, attendanceEntries] = await Promise.all([
        this.storeService.getAppSettings(),
        this.storeService.getStaffMembers(),
        this.storeService.getDailySales(),
        this.storeService.getAttendanceEntries(),
      ]);

      this.appSettings.set(appSettings);
      this.staffMembers.set(staffMembers);
      this.dailySales.set(dailySales);
      this.attendanceEntries.set(attendanceEntries);
      this.ensureSelectedStaffMember();
      this.ensureSelectedAttendanceStaffMember();
    } finally {
      this.isLoading.set(false);
    }
  }

  private clearDataState(): void {
    this.currentSection.set('dashboard');
    this.isSidebarOpen.set(false);
    this.appSettings.set({ companyClosureDays: ['domenica'] });
    this.staffMembers.set([]);
    this.dailySales.set([]);
    this.attendanceEntries.set([]);
    this.editingStaffMemberId.set(null);
    this.editingAttendanceEntryId.set(null);
    this.resetStaffForm();
    this.saleForm.saleDate = this.today();
    this.saleForm.staffMemberId = '';
    this.saleForm.regularAmount = 0;
    this.saleForm.testAmount = 0;
    this.saleForm.notes = '';
    this.resetAttendanceForm();
    this.attendanceFilter.staffMemberId = '';
    this.attendanceFilter.month = this.today().slice(5, 7);
    this.attendanceFilter.year = String(new Date().getFullYear());
  }

  private filterSalesByMonth(sales: DailySale[], month: string, year: string): DailySale[] {
    return sales.filter((sale) => sale.saleDate.startsWith(`${year}-${month}`));
  }

  private filterAttendanceByMonth(entries: AttendanceEntry[], month: string, year: string): AttendanceEntry[] {
    return [...entries]
      .filter((entry) => entry.entryDate.startsWith(`${year}-${month}`))
      .sort((left, right) => right.entryDate.localeCompare(left.entryDate));
  }

  private getSalesForStaffInCurrentReport(staffMemberId: string): DailySale[] {
    return this.filteredReportSales().filter((sale) => sale.staffMemberId === staffMemberId);
  }

  private ownerCount(excludedStaffMemberId?: string | null): number {
    return this.activeStaffMembers().filter(
      (member) => member.role === 'titolare' && member.id !== excludedStaffMemberId,
    ).length;
  }

  private employeeCount(excludedStaffMemberId?: string | null): number {
    return this.activeStaffMembers().filter(
      (member) => member.role === 'dipendente' && member.id !== excludedStaffMemberId,
    ).length;
  }

  private normalizeAmount(amount: number): number {
    return Math.round(amount * 100) / 100;
  }

  private toInputDate(date: Date): string {
    const year = date.getFullYear();
    const month = String(date.getMonth() + 1).padStart(2, '0');
    const day = String(date.getDate()).padStart(2, '0');
    return `${year}-${month}-${day}`;
  }

  private formatCurrency(amount: number): string {
    return new Intl.NumberFormat(this.locale, {
      style: 'currency',
      currency: this.currencyCode,
      minimumFractionDigits: 2,
    }).format(amount);
  }

  private formatDate(date: string): string {
    return new Intl.DateTimeFormat(this.locale).format(new Date(date));
  }

  private ensureSelectedStaffMember(): void {
    const activeStaffMembers = this.activeStaffMembers();
    const currentSelectedId = this.saleForm.staffMemberId;

    if (activeStaffMembers.some((member) => member.id === currentSelectedId)) {
      return;
    }

    this.saleForm.staffMemberId = activeStaffMembers[0]?.id ?? '';
  }

  private ensureSelectedAttendanceStaffMember(): void {
    const activeEmployeeStaffMembers = this.activeEmployeeStaffMembers();

    if (!activeEmployeeStaffMembers.some((staffMember) => staffMember.id === this.attendanceForm.staffMemberId)) {
      this.attendanceForm.staffMemberId = activeEmployeeStaffMembers[0]?.id ?? '';
    }

    if (!this.employeeStaffMembers().some((staffMember) => staffMember.id === this.attendanceFilter.staffMemberId)) {
      this.attendanceFilter.staffMemberId =
        this.employeeStaffMembers()[0]?.id ?? '';
    }

    this.onAttendanceStaffChange();
  }

  private getSelectedAttendanceStaffMember(): StaffMember | undefined {
    return this.employeeStaffMembers().find((staffMember) => staffMember.id === this.attendanceForm.staffMemberId);
  }

  private getAttendanceStaffMemberById(staffMemberId: string): StaffMember | undefined {
    return this.employeeStaffMembers().find((staffMember) => staffMember.id === staffMemberId);
  }

  private getWeekdayKeyFromDate(isoDate: string): WeekdayKey {
    const [yearValue, monthValue, dayValue] = isoDate.split('-');
    const year = Number.parseInt(yearValue, 10);
    const month = Number.parseInt(monthValue, 10);
    const day = Number.parseInt(dayValue, 10);
    const date = new Date(year, month - 1, day);
    const weekdayMap: WeekdayKey[] = ['domenica', 'lunedi', 'martedi', 'mercoledi', 'giovedi', 'venerdi', 'sabato'];
    return weekdayMap[date.getDay()];
  }

  private getPlannedShiftForDate(staffMember: StaffMember, isoDate: string) {
    const weekdayKey = this.getWeekdayKeyFromDate(isoDate);

    if (this.isCompanyClosureDay(weekdayKey) || this.isNationalHolidayDate(isoDate)) {
      return {
        isWorking: false,
        hours: 0,
      };
    }

    return staffMember.weeklySchedule[weekdayKey];
  }

  private buildMonthlyAttendanceEntries(staffMemberId: string): EffectiveAttendanceEntry[] {
    const staffMember = this.getAttendanceStaffMemberById(staffMemberId);

    if (!staffMember) {
      return [];
    }

    const explicitEntries = this.filteredAttendanceEntries()
      .filter((entry) => entry.staffMemberId === staffMemberId)
      .map((entry) => ({ ...entry, isAutoGenerated: false as const }));
    const explicitEntryMap = new Map(explicitEntries.map((entry) => [entry.entryDate, entry]));
    const year = Number.parseInt(this.attendanceFilter.year, 10);
    const monthIndex = Number.parseInt(this.attendanceFilter.month, 10) - 1;
    const lastDay = new Date(year, monthIndex + 1, 0);
    const employeeStartDate = staffMember.createdAt.slice(0, 10);
    const effectiveEntries: EffectiveAttendanceEntry[] = [];

    for (let day = 1; day <= lastDay.getDate(); day += 1) {
      const isoDate = this.toInputDate(new Date(year, monthIndex, day));
      const explicitEntry = explicitEntryMap.get(isoDate);

      if (explicitEntry) {
        effectiveEntries.push(explicitEntry);
        continue;
      }

      if (isoDate < employeeStartDate) {
        continue;
      }

      if (isoDate > this.today()) {
        continue;
      }

      const plannedShift = this.getPlannedShiftForDate(staffMember, isoDate);

      if (!plannedShift.isWorking) {
        continue;
      }

      effectiveEntries.push({
        id: `auto-${staffMemberId}-${isoDate}`,
        staffMemberId,
        entryDate: isoDate,
        entryType: 'lavoro',
        workedHours: plannedShift.hours,
        notes: 'Turno previsto',
        createdAt: isoDate,
        isAutoGenerated: true,
      });
    }

    return effectiveEntries.sort((left, right) => right.entryDate.localeCompare(left.entryDate));
  }

  private buildAttendanceSummary(entries: EffectiveAttendanceEntry[]): AttendanceSummary {
    return entries.reduce(
      (summary, entry) => {
        summary.totalWorkedHours += entry.workedHours;

        if (entry.entryType === 'lavoro') {
          summary.workDays += 1;
        }

        if (entry.entryType === 'festivo') {
          summary.holidayDays += 1;
        }

        if (entry.entryType === 'ferie') {
          summary.vacationDays += 1;
        }

        if (entry.entryType === 'permesso') {
          summary.permitDays += 1;
        }

        if (entry.entryType === 'malattia') {
          summary.sickDays += 1;
        }

        return summary;
      },
      {
        totalWorkedHours: 0,
        workDays: 0,
        holidayDays: 0,
        vacationDays: 0,
        permitDays: 0,
        sickDays: 0,
      },
    );
  }

  private getDateRange(startDate: string, endDate: string): string[] {
    const dates: string[] = [];
    const cursor = new Date(startDate);
    const finalDate = new Date(endDate);

    while (cursor <= finalDate) {
      dates.push(this.toInputDate(cursor));
      cursor.setDate(cursor.getDate() + 1);
    }

    return dates;
  }

  private findConflictingExplicitEntry(targetDates: string[], excludedEntryId: string | null): AttendanceEntry | undefined {
    return this.attendanceEntries().find(
      (entry) =>
        entry.staffMemberId === this.attendanceForm.staffMemberId &&
        targetDates.includes(entry.entryDate) &&
        entry.id !== excludedEntryId,
    );
  }

  private isCompanyClosureDate(isoDate: string): boolean {
    return this.isCompanyClosureDay(this.getWeekdayKeyFromDate(isoDate));
  }

  private isNationalHolidayDate(isoDate: string): boolean {
    const fixedNationalHolidays = new Set([
      '01-01',
      '01-06',
      '04-25',
      '05-01',
      '06-02',
      '08-15',
      '11-01',
      '12-08',
      '12-25',
      '12-26',
    ]);
    const monthDay = isoDate.slice(5, 10);

    if (fixedNationalHolidays.has(monthDay)) {
      return true;
    }

    const easterMonday = this.getEasterMondayIsoDate(Number.parseInt(isoDate.slice(0, 4), 10));
    return isoDate === easterMonday;
  }

  private getEasterMondayIsoDate(year: number): string {
    const easterDate = this.getEasterDate(year);
    easterDate.setDate(easterDate.getDate() + 1);
    return this.toInputDate(easterDate);
  }

  private getEasterDate(year: number): Date {
    const century = Math.floor(year / 100);
    const yearInCentury = year % 100;
    const leapCenturyAdjust = Math.floor(century / 4);
    const centuryRemainder = century % 4;
    const correction = Math.floor((century + 8) / 25);
    const moonCorrection = Math.floor((century - correction + 1) / 3);
    const epact = (19 * (year % 19) + century - leapCenturyAdjust - moonCorrection + 15) % 30;
    const yearQuarter = Math.floor(yearInCentury / 4);
    const yearRemainder = yearInCentury % 4;
    const weekdayCorrection = (32 + 2 * centuryRemainder + 2 * yearQuarter - epact - yearRemainder) % 7;
    const monthAdjust = Math.floor((year % 19 + 11 * epact + 22 * weekdayCorrection) / 451);
    const month = Math.floor((epact + weekdayCorrection - 7 * monthAdjust + 114) / 31);
    const day = ((epact + weekdayCorrection - 7 * monthAdjust + 114) % 31) + 1;
    return new Date(year, month - 1, day);
  }

  private getWeeklyScheduleValidationError(weeklySchedule: WeeklyShiftTemplate): string | null {
    for (const weekday of this.weekdayOptions) {
      const dayConfig = weeklySchedule[weekday.key];

      if (this.isCompanyClosureDay(weekday.key) && dayConfig.isWorking) {
        return `Non puoi impostare ${weekday.label} come lavorativo se l'azienda e chiusa.`;
      }

      if (dayConfig.isWorking && dayConfig.hours <= 0) {
        return `Inserisci ore maggiori di zero per ${weekday.label}.`;
      }

      if (!dayConfig.isWorking && dayConfig.hours !== 0) {
        return `Per ${weekday.label} non lavorativo le ore devono essere zero.`;
      }
    }

    return null;
  }

  private normalizeWeeklyScheduleForm(weeklySchedule: WeeklyShiftTemplate): WeeklyShiftTemplate {
    const normalizedSchedule = this.cloneWeeklySchedule(weeklySchedule);

    for (const weekday of this.weekdayOptions) {
      if (this.isCompanyClosureDay(weekday.key)) {
        normalizedSchedule[weekday.key] = {
          isWorking: false,
          hours: 0,
        };
        continue;
      }

      normalizedSchedule[weekday.key] = {
        isWorking: normalizedSchedule[weekday.key].isWorking,
        hours: normalizedSchedule[weekday.key].isWorking
          ? this.normalizeAmount(normalizedSchedule[weekday.key].hours)
          : 0,
      };
    }

    return normalizedSchedule;
  }

  private cloneWeeklySchedule(weeklySchedule: WeeklyShiftTemplate): WeeklyShiftTemplate {
    return {
      lunedi: { ...weeklySchedule.lunedi },
      martedi: { ...weeklySchedule.martedi },
      mercoledi: { ...weeklySchedule.mercoledi },
      giovedi: { ...weeklySchedule.giovedi },
      venerdi: { ...weeklySchedule.venerdi },
      sabato: { ...weeklySchedule.sabato },
      domenica: { ...weeklySchedule.domenica },
    };
  }

  protected getAttendanceTypeLabel(entryType: AttendanceType): string {
    return this.attendanceTypeOptions.find((option) => option.value === entryType)?.label ?? 'Presenza';
  }

  protected isHolidayDate(isoDate: string): boolean {
    return this.isCompanyClosureDate(isoDate) || this.isNationalHolidayDate(isoDate);
  }

  protected getAttendanceDayCardClass(isoDate: string, entry: AttendanceEntry | null): string {
    if (entry) {
      return `attendance-day attendance-day-${entry.entryType}`;
    }

    if (this.isHolidayDate(isoDate)) {
      return 'attendance-day attendance-day-festivo';
    }

    return 'attendance-day attendance-day-empty';
  }

  protected getAttendanceDayListCopy(day: AttendanceCalendarDay): string {
    if (day.entry) {
      if (day.entry.entryType === 'ferie') {
        return 'Ferie';
      }

      if (day.entry.entryType === 'malattia') {
        return 'Malattia';
      }

      if (day.entry.entryType === 'festivo') {
        return 'Chiuso';
      }

      return `${this.getAttendanceTypeLabel(day.entry.entryType)} · ${this.formatCompactHours(day.entry.workedHours)}h`;
    }

    if (day.isCompanyClosed) {
      return 'Chiuso';
    }

    if (day.isNationalHoliday) {
      return 'Festivo nazionale';
    }

    if (day.plannedShift?.isWorking) {
      return `${this.formatCompactHours(day.plannedShift.hours)}h previste`;
    }

    return 'Non lavorativo';
  }

  private resetStaffForm(): void {
    this.editingStaffMemberId.set(null);
    this.staffForm.fullName = '';
    this.staffForm.role = 'dipendente';
    this.staffForm.defaultDailyHours = 8;
    this.staffForm.weeklySchedule = createWeeklyShiftTemplate(8);
  }

  private resetAttendanceForm(): void {
    this.editingAttendanceEntryId.set(null);
    this.attendanceForm.entryDate = this.today();
    this.attendanceForm.endDate = this.today();
    this.attendanceForm.entryType = 'lavoro';
    this.attendanceForm.notes = '';
    this.onAttendanceStaffChange();
  }

  private setFeedback(type: 'success' | 'error' | 'info', message: string): void {
    if (this.feedbackTimeoutId) {
      window.clearTimeout(this.feedbackTimeoutId);
    }

    this.feedback.set({ type, message });
    this.feedbackTimeoutId = window.setTimeout(() => {
      this.feedback.set(null);
      this.feedbackTimeoutId = null;
    }, 2800);
  }

  private formatCompactHours(hours: number): string {
    return Number.isInteger(hours) ? String(hours) : String(hours).replace('.', ',');
  }

  private getErrorMessage(error: unknown, fallbackMessage: string): string {
    if (error instanceof Error && error.message) {
      return error.message;
    }

    return fallbackMessage;
  }
}
