import { CommonModule, CurrencyPipe, DatePipe, registerLocaleData } from '@angular/common';
import localeIt from '@angular/common/locales/it';
import { AfterViewChecked, Component, computed, inject, OnDestroy, OnInit, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Session } from '@supabase/supabase-js';

import {
  AppSettings,
  AttendanceEntry,
  AttendanceSummary,
  AttendanceType,
  createWeeklyShiftTemplate,
  DailySale,
  PersonRole,
  StaffMember,
  StaffPerformance,
  WEEKDAY_OPTIONS,
  WeekdayKey,
  WeeklyShiftTemplate,
} from './models/store.models';
import { StoreService } from './services/store.service';

registerLocaleData(localeIt);

type AppSection = 'dashboard' | 'incasso' | 'report' | 'presenze' | 'impostazioni';
type AuthMode = 'sign-in' | 'sign-up';

type EffectiveAttendanceEntry = AttendanceEntry & { isAutoGenerated: boolean };
type AttendanceCalendarDay = {
  isoDate: string;
  dayNumber: number;
  weekdayLabel: string;
  isWeekend: boolean;
  weekdayKey: WeekdayKey;
  isCompanyClosed: boolean;
  isNationalHoliday: boolean;
  plannedShift: { isWorking: boolean; hours: number } | null;
  entry: EffectiveAttendanceEntry | null;
};
type StaffAttendanceMonthRow = {
  staffMember: StaffMember;
  summary: AttendanceSummary;
  annualSummary: AttendanceSummary;
};
type ReportOverviewCard = {
  staffMember: StaffMember;
  totalAmount: number;
  workedDays: number;
  trendPercentage: number | null;
  previousTotalAmount: number;
};
type ReportMonthlyPerformanceRow = {
  monthKey: string;
  label: string;
  totalAmount: number;
  regularAmount: number;
  testAmount: number;
  workedDays: number;
  averageDaily: number;
};
type ReportDailyPerformanceRow = {
  isoDate: string;
  label: string;
  totalAmount: number;
  regularAmount: number;
  testAmount: number;
};
type ReportAttendanceDetailRow = {
  isoDate: string;
  label: string;
  typeLabel: string;
  workedHours: number;
  notes: string;
  sourceLabel: string;
};
type ReportDistributionSlice = {
  label: string;
  value: number;
  color: string;
};
type ReportDetailMetrics = {
  totalAmount: number;
  totalRegular: number;
  totalTest: number;
  averageDaily: number;
  workedDays: number;
  absenceDays: number;
  productivityIndex: number;
  plannedWorkingDays: number;
  vacationAccrued: number;
  vacationUsed: number;
  permitDays: number;
  sickDays: number;
};

@Component({
  selector: 'app-root',
  imports: [CommonModule, FormsModule, CurrencyPipe, DatePipe],
  templateUrl: './app.html',
  styleUrl: './app.scss',
})
export class App implements OnInit, OnDestroy, AfterViewChecked {
  private readonly storeService = inject(StoreService);
  private feedbackTimeoutId: ReturnType<typeof window.setTimeout> | null = null;
  private remoteReloadTimeoutId: ReturnType<typeof window.setTimeout> | null = null;
  private readonly attendanceEditWindowDays = 3;
  private reportDetailChartsRenderKey = '';
  private reportChartLibraryPromise: Promise<typeof import('chart.js/auto')> | null = null;
  private readonly reportChartInstances = new Map<string, { destroy: () => void; toBase64Image: () => string }>();
  private authSubscription: { unsubscribe: () => void } | null = null;
  private dataSyncSubscription: { unsubscribe: () => void } | null = null;
  private loadedUserId: string | null = null;
  private loadingUserId: string | null = null;
  private dataSyncUserId: string | null = null;
  private readonly currentDateTimerId = window.setInterval(() => {
    this.currentDate.set(this.toInputDate(new Date()));
  }, 60_000);

  protected readonly title = 'Goldfinger Manager';
  protected readonly locale = 'it-IT';
  protected readonly currencyCode = 'EUR';
  protected readonly currentDate = signal(this.toInputDate(new Date()));
  protected readonly today = this.currentDate.asReadonly();
  protected readonly authSession = signal<Session | null>(null);
  protected readonly isAuthReady = signal(false);
  protected readonly isAuthProcessing = signal(false);
  protected readonly authMode = signal<AuthMode>('sign-in');
  protected readonly showAuthPassword = signal(false);
  protected readonly showAuthConfirmPassword = signal(false);
  protected readonly currentSection = signal<AppSection>('dashboard');
  protected readonly isSidebarOpen = signal(false);
  protected readonly feedback = signal<{ type: 'success' | 'error' | 'info'; message: string } | null>(
    null,
  );
  protected readonly isLoading = signal(true);
  protected readonly isSavingStaff = signal(false);
  protected readonly isSavingSale = signal(false);
  protected readonly isSavingAttendance = signal(false);
  protected readonly isSavingSettings = signal(false);
  protected readonly isAttendanceModalOpen = signal(false);
  protected readonly attendanceFilterVersion = signal(0);
  protected readonly appSettings = signal<AppSettings>({ companyClosureDays: ['domenica'] });
  protected readonly staffMembers = signal<StaffMember[]>([]);
  protected readonly dailySales = signal<DailySale[]>([]);
  protected readonly attendanceEntries = signal<AttendanceEntry[]>([]);
  protected readonly editingStaffMemberId = signal<string | null>(null);
  protected readonly menuItems: Array<{ id: AppSection; label: string }> = [
    { id: 'dashboard', label: 'Dashboard' },
    { id: 'incasso', label: 'Incasso' },
    { id: 'report', label: 'Report' },
    { id: 'presenze', label: 'Presenze' },
    { id: 'impostazioni', label: 'Impostazioni' },
  ];
  protected readonly weekdayOptions = WEEKDAY_OPTIONS;
  protected readonly authForm = {
    email: '',
    password: '',
    confirmPassword: '',
  };

  protected readonly staffForm = {
    fullName: '',
    role: 'dipendente' as PersonRole,
    defaultDailyHours: 8,
    weeklySchedule: createWeeklyShiftTemplate(8),
  };

  protected readonly saleForm = {
    saleDate: this.today(),
    staffMemberId: '',
    regularAmount: 0,
    testAmount: 0,
    notes: '',
  };

  protected readonly reportFilter = {
    month: this.today().slice(5, 7),
    year: String(new Date().getFullYear()),
    startDate: `${this.today().slice(0, 8)}01`,
    endDate: this.toInputDate(new Date(new Date().getFullYear(), new Date().getMonth() + 1, 0)),
  };
  protected readonly selectedReportStaffMemberId = signal<string | null>(null);
  protected readonly reportDetailFilter = {
    startDate: `${this.today().slice(0, 8)}01`,
    endDate: this.toInputDate(new Date(new Date().getFullYear(), new Date().getMonth() + 1, 0)),
  };
  protected readonly reportMonthOptions = [
    { value: '01', label: 'Gennaio' },
    { value: '02', label: 'Febbraio' },
    { value: '03', label: 'Marzo' },
    { value: '04', label: 'Aprile' },
    { value: '05', label: 'Maggio' },
    { value: '06', label: 'Giugno' },
    { value: '07', label: 'Luglio' },
    { value: '08', label: 'Agosto' },
    { value: '09', label: 'Settembre' },
    { value: '10', label: 'Ottobre' },
    { value: '11', label: 'Novembre' },
    { value: '12', label: 'Dicembre' },
  ];
  protected readonly attendanceTypeOptions: Array<{ value: AttendanceType; label: string }> = [
    { value: 'lavoro', label: 'Lavoro' },
    { value: 'festivo', label: 'Festivo' },
    { value: 'ferie', label: 'Ferie' },
    { value: 'permesso', label: 'Permesso' },
    { value: 'malattia', label: 'Malattia' },
  ];
  protected readonly attendanceForm = {
    staffMemberId: '',
    entryDate: this.today(),
    endDate: this.today(),
    entryType: 'lavoro' as AttendanceType,
    workedHours: 8,
    notes: '',
  };
  protected readonly editingAttendanceEntryId = signal<string | null>(null);
  protected readonly editingAttendanceEntryIds = signal<string[]>([]);
  protected readonly selectedAttendanceStaffMemberId = signal('');
  protected readonly attendanceFilter = {
    month: this.today().slice(5, 7),
    year: String(new Date().getFullYear()),
    staffMemberId: '',
  };

  protected readonly currentSectionLabel = computed(() =>
    this.menuItems.find((item) => item.id === this.currentSection())?.label ?? 'Dashboard',
  );
  protected readonly isAuthenticated = computed(() => !!this.authSession());
  protected readonly currentUserEmail = computed(() => this.authSession()?.user.email ?? '');

  protected readonly staffMemberMap = computed(
    () => new Map(this.staffMembers().map((member) => [member.id, member])),
  );

  protected readonly activeStaffMembers = computed(() =>
    this.staffMembers().filter((member) => member.isActive),
  );

  protected readonly hiddenStaffMembers = computed(() =>
    this.staffMembers().filter((member) => !member.isActive),
  );

  protected readonly employeeStaffMembers = computed(() =>
    this.staffMembers().filter((member) => member.role === 'dipendente'),
  );

  protected readonly activeEmployeeStaffMembers = computed(() =>
    this.activeStaffMembers().filter((member) => member.role === 'dipendente'),
  );

  protected readonly orderedSales = computed(() =>
    [...this.dailySales()].sort((left, right) => {
      const dateComparison = right.saleDate.localeCompare(left.saleDate);

      if (dateComparison !== 0) {
        return dateComparison;
      }

      return right.createdAt.localeCompare(left.createdAt);
    }),
  );

  protected readonly filteredReportSales = computed(() =>
    this.filterSalesByDateRange(this.orderedSales(), this.reportFilter.startDate, this.reportFilter.endDate),
  );

  protected readonly filteredReportTotal = computed(() =>
    this.filteredReportSales().reduce((total, sale) => total + sale.regularAmount + sale.testAmount, 0),
  );

  protected readonly totalRegular = computed(() =>
    this.dailySales().reduce((total, sale) => total + sale.regularAmount, 0),
  );

  protected readonly totalTest = computed(() =>
    this.dailySales().reduce((total, sale) => total + sale.testAmount, 0),
  );

  protected readonly totalAmount = computed(() => this.totalRegular() + this.totalTest());

  protected readonly todayTotal = computed(() =>
    this.dailySales()
      .filter((sale) => sale.saleDate === this.today())
      .reduce((total, sale) => total + sale.regularAmount + sale.testAmount, 0),
  );

  protected readonly currentMonthTotal = computed(() =>
    this.dailySales()
      .filter((sale) => sale.saleDate.startsWith(this.today().slice(0, 7)))
      .reduce((total, sale) => total + sale.regularAmount + sale.testAmount, 0),
  );

  protected readonly currentMonthLabel = computed(() =>
    new Intl.DateTimeFormat(this.locale, { month: 'long', year: 'numeric' }).format(new Date()),
  );

  protected readonly recentSales = computed(() => this.orderedSales().slice(0, 5));

  protected readonly availableReportYears = computed(() => {
    const currentYear = new Date().getFullYear();
    const saleYears = this.dailySales().map((sale) => Number.parseInt(sale.saleDate.slice(0, 4), 10));
    const earliestYear = saleYears.length ? Math.min(...saleYears) : currentYear;
    const years: string[] = [];

    for (let year = currentYear; year >= earliestYear; year -= 1) {
      years.push(String(year));
    }

    return years;
  });

  protected readonly availableAttendanceYears = computed(() => {
    const currentYear = new Date().getFullYear();
    const attendanceYears = this.attendanceEntries().map((entry) => Number.parseInt(entry.entryDate.slice(0, 4), 10));
    const earliestYear = attendanceYears.length ? Math.min(...attendanceYears) : currentYear;
    const years: string[] = [];

    for (let year = currentYear; year >= earliestYear; year -= 1) {
      years.push(String(year));
    }

    return years;
  });

  protected readonly reportPeriodLabel = computed(() => {
    if (!this.reportFilter.startDate || !this.reportFilter.endDate) {
      return 'Periodo non selezionato';
    }

    if (this.isWholeSelectedMonthRange()) {
    const monthLabel =
      this.reportMonthOptions.find((month) => month.value === this.reportFilter.month)?.label ?? 'Mese';
      return `${monthLabel} ${this.reportFilter.year}`;
    }

    return `${this.formatDate(this.reportFilter.startDate)} - ${this.formatDate(this.reportFilter.endDate)}`;
  });

  protected readonly attendancePeriodLabel = computed(() => {
    const monthLabel =
      this.reportMonthOptions.find((month) => month.value === this.attendanceFilter.month)?.label ?? 'Mese';
    return `${monthLabel} ${this.attendanceFilter.year}`;
  });

  protected readonly reportRows = computed<StaffPerformance[]>(() => {
    const salesByStaffMember = new Map<string, DailySale[]>();

    for (const sale of this.filteredReportSales()) {
      const collection = salesByStaffMember.get(sale.staffMemberId) ?? [];
      collection.push(sale);
      salesByStaffMember.set(sale.staffMemberId, collection);
    }

    return this.staffMembers()
      .map((staffMember) => {
        const sales = salesByStaffMember.get(staffMember.id) ?? [];
        const totalRegular = sales.reduce((total, sale) => total + sale.regularAmount, 0);
        const totalTest = sales.reduce((total, sale) => total + sale.testAmount, 0);
        const workedDays = new Set(sales.map((sale) => sale.saleDate)).size;
        const totalAmount = totalRegular + totalTest;

        return {
          staffMember,
          totalRegular,
          totalTest,
          totalAmount,
          daysWorked: workedDays,
          averageDaily: workedDays > 0 ? totalAmount / workedDays : 0,
        };
      })
      .filter((row) => row.staffMember.isActive || row.totalAmount > 0)
      .sort((left, right) => right.totalAmount - left.totalAmount);
  });

  protected readonly reportMaxTotal = computed(() =>
    this.reportRows().reduce((maxValue, row) => Math.max(maxValue, row.totalAmount), 0),
  );

  protected readonly monthlySales = computed(() => this.filteredReportSales());

  protected readonly reportOverviewCards = computed<ReportOverviewCard[]>(() => {
    const { startDate, endDate } = this.getMonthDateRangeFromIsoDate(this.today());
    const previousMonthReference = this.shiftIsoDate(startDate, -1);
    const previousRange = this.getMonthDateRangeFromIsoDate(previousMonthReference);

    return this.staffMembers()
      .filter((staffMember) => staffMember.isActive || this.hasStaffSales(staffMember.id))
      .map((staffMember) => {
        const currentSales = this.getSalesForStaffInRange(staffMember.id, startDate, endDate);
        const previousSales = this.getSalesForStaffInRange(staffMember.id, previousRange.startDate, previousRange.endDate);
        const totalAmount = this.sumSalesAmount(currentSales);
        const previousTotalAmount = this.sumSalesAmount(previousSales);

        return {
          staffMember,
          totalAmount,
          workedDays: new Set(currentSales.map((sale) => sale.saleDate)).size,
          trendPercentage: this.calculateTrendPercentage(totalAmount, previousTotalAmount),
          previousTotalAmount,
        };
      })
      .sort((left, right) => right.totalAmount - left.totalAmount || left.staffMember.fullName.localeCompare(right.staffMember.fullName));
  });

  protected readonly selectedReportStaffMember = computed<StaffMember | null>(() => {
    const selectedStaffMemberId = this.selectedReportStaffMemberId();

    if (!selectedStaffMemberId) {
      return null;
    }

    return this.staffMembers().find((staffMember) => staffMember.id === selectedStaffMemberId) ?? null;
  });

  protected readonly reportDetailSales = computed<DailySale[]>(() => {
    const selectedStaffMember = this.selectedReportStaffMember();

    if (!selectedStaffMember) {
      return [];
    }

    return this.getSalesForStaffInRange(
      selectedStaffMember.id,
      this.reportDetailFilter.startDate,
      this.reportDetailFilter.endDate,
    ).sort((left, right) => left.saleDate.localeCompare(right.saleDate));
  });

  protected readonly reportDetailAttendanceEntries = computed<EffectiveAttendanceEntry[]>(() => {
    const selectedStaffMember = this.selectedReportStaffMember();

    if (!selectedStaffMember) {
      return [];
    }

    return this.buildAttendanceEntriesForRange(
      selectedStaffMember.id,
      this.reportDetailFilter.startDate,
      this.reportDetailFilter.endDate,
    ).sort((left, right) => left.entryDate.localeCompare(right.entryDate));
  });

  protected readonly reportDetailAttendanceSummary = computed<AttendanceSummary>(() =>
    this.buildAttendanceSummary(this.reportDetailAttendanceEntries()),
  );

  protected readonly reportDetailMetrics = computed<ReportDetailMetrics>(() => {
    const selectedStaffMember = this.selectedReportStaffMember();
    const sales = this.reportDetailSales();
    const attendanceSummary = this.reportDetailAttendanceSummary();
    const totalAmount = this.sumSalesAmount(sales);
    const workedDays = new Set(sales.map((sale) => sale.saleDate)).size;
    const plannedWorkingDays = selectedStaffMember
      ? this.getPlannedWorkingDaysInRange(
          selectedStaffMember,
          this.reportDetailFilter.startDate,
          this.reportDetailFilter.endDate,
        )
      : 0;
    const absenceDays = attendanceSummary.vacationDays + attendanceSummary.permitDays + attendanceSummary.sickDays;

    return {
      totalAmount,
      totalRegular: sales.reduce((total, sale) => total + sale.regularAmount, 0),
      totalTest: sales.reduce((total, sale) => total + sale.testAmount, 0),
      averageDaily: workedDays > 0 ? totalAmount / workedDays : 0,
      workedDays,
      absenceDays,
      productivityIndex: plannedWorkingDays > 0 ? (workedDays / plannedWorkingDays) * 100 : 0,
      plannedWorkingDays,
      vacationAccrued: selectedStaffMember
        ? this.calculateVacationAccrual(selectedStaffMember, this.reportDetailFilter.startDate, this.reportDetailFilter.endDate)
        : 0,
      vacationUsed: attendanceSummary.vacationDays,
      permitDays: attendanceSummary.permitDays,
      sickDays: attendanceSummary.sickDays,
    };
  });

  protected readonly reportDetailMonthlyRows = computed<ReportMonthlyPerformanceRow[]>(() => {
    const salesByMonth = new Map<string, DailySale[]>();

    for (const sale of this.reportDetailSales()) {
      const monthKey = sale.saleDate.slice(0, 7);
      const collection = salesByMonth.get(monthKey) ?? [];
      collection.push(sale);
      salesByMonth.set(monthKey, collection);
    }

    return [...salesByMonth.entries()]
      .map(([monthKey, sales]) => {
        const totalAmount = this.sumSalesAmount(sales);
        const workedDays = new Set(sales.map((sale) => sale.saleDate)).size;
        const monthDate = `${monthKey}-01`;

        return {
          monthKey,
          label: new Intl.DateTimeFormat(this.locale, { month: 'long', year: 'numeric' }).format(new Date(monthDate)),
          totalAmount,
          regularAmount: sales.reduce((total, sale) => total + sale.regularAmount, 0),
          testAmount: sales.reduce((total, sale) => total + sale.testAmount, 0),
          workedDays,
          averageDaily: workedDays > 0 ? totalAmount / workedDays : 0,
        };
      })
      .sort((left, right) => left.monthKey.localeCompare(right.monthKey));
  });

  protected readonly reportDetailDailyRows = computed<ReportDailyPerformanceRow[]>(() =>
    this.reportDetailSales().map((sale) => ({
      isoDate: sale.saleDate,
      label: this.formatDate(sale.saleDate),
      totalAmount: sale.regularAmount + sale.testAmount,
      regularAmount: sale.regularAmount,
      testAmount: sale.testAmount,
    })),
  );

  protected readonly reportDetailAttendanceRows = computed<ReportAttendanceDetailRow[]>(() =>
    [...this.reportDetailAttendanceEntries()]
      .sort((left, right) => right.entryDate.localeCompare(left.entryDate))
      .map((entry) => ({
        isoDate: entry.entryDate,
        label: this.formatDate(entry.entryDate),
        typeLabel: entry.isAutoGenerated && entry.entryType === 'lavoro' ? 'Lavoro pianificato' : this.getAttendanceTypeLabel(entry.entryType),
        workedHours: entry.workedHours,
        notes: entry.notes || '-',
        sourceLabel: entry.isAutoGenerated ? 'Sistema' : 'Manuale',
      })),
  );

  protected readonly reportDetailDistribution = computed<ReportDistributionSlice[]>(() => {
    const attendanceSummary = this.reportDetailAttendanceSummary();

    return [
      { label: 'Presenze', value: attendanceSummary.workDays, color: '#2563eb' },
      { label: 'Ferie', value: attendanceSummary.vacationDays, color: '#059669' },
      { label: 'Malattie', value: attendanceSummary.sickDays, color: '#dc2626' },
    ];
  });

  protected readonly reportDetailPeriodLabel = computed(() => {
    if (!this.reportDetailFilter.startDate || !this.reportDetailFilter.endDate) {
      return 'Periodo non selezionato';
    }

    return `${this.formatDate(this.reportDetailFilter.startDate)} - ${this.formatDate(this.reportDetailFilter.endDate)}`;
  });

  protected readonly reportDetailHasData = computed(() =>
    this.reportDetailSales().length > 0 || this.reportDetailAttendanceRows().length > 0,
  );

  protected onReportMonthYearChange(): void {
    const { startDate, endDate } = this.getMonthDateRange(this.reportFilter.year, this.reportFilter.month);
    this.reportFilter.startDate = startDate;
    this.reportFilter.endDate = endDate;
  }

  protected onReportDateRangeChange(): void {
    if (!this.reportFilter.startDate || !this.reportFilter.endDate) {
      return;
    }

    if (this.reportFilter.endDate < this.reportFilter.startDate) {
      this.reportFilter.endDate = this.reportFilter.startDate;
    }

    this.reportFilter.month = this.reportFilter.startDate.slice(5, 7);
    this.reportFilter.year = this.reportFilter.startDate.slice(0, 4);
  }

  protected openReportStaffDetail(staffMemberId: string): void {
    this.selectedReportStaffMemberId.set(staffMemberId);
  }

  protected closeReportStaffDetail(): void {
    this.selectedReportStaffMemberId.set(null);
  }

  protected onReportDetailDateRangeChange(): void {
    if (!this.reportDetailFilter.startDate || !this.reportDetailFilter.endDate) {
      return;
    }

    if (this.reportDetailFilter.endDate < this.reportDetailFilter.startDate) {
      this.reportDetailFilter.endDate = this.reportDetailFilter.startDate;
    }
  }

  protected formatReportDateButton(date: string): string {
    if (!date) {
      return '--';
    }

    return new Intl.DateTimeFormat(this.locale, {
      day: 'numeric',
      month: 'short',
      year: 'numeric',
    }).format(new Date(date));
  }

  protected formatTrendValue(trendPercentage: number | null): string {
    if (trendPercentage === null) {
      return 'Nuovo';
    }

    const roundedTrend = Math.round(trendPercentage * 10) / 10;
    const prefix = roundedTrend > 0 ? '+' : '';
    return `${prefix}${roundedTrend}%`;
  }

  protected getTrendClass(trendPercentage: number | null): string {
    if (trendPercentage === null || trendPercentage === 0) {
      return 'report-trend-neutral';
    }

    return trendPercentage > 0 ? 'report-trend-up' : 'report-trend-down';
  }

  protected formatProductivityIndex(value: number): string {
    return `${Math.round(value)}%`;
  }

  protected readonly filteredAttendanceEntries = computed(() =>
    (this.attendanceFilterVersion(),
    this.filterAttendanceByMonth(this.attendanceEntries(), this.attendanceFilter.month, this.attendanceFilter.year)),
  );

  protected readonly explicitAttendanceEntriesForSelectedStaff = computed(() => {
    this.attendanceFilterVersion();
    const selectedStaffMemberId = this.selectedAttendanceStaffMemberId();
    return this.filteredAttendanceEntries().filter((entry) => entry.staffMemberId === selectedStaffMemberId);
  });

  protected readonly attendanceEntriesForSelectedStaff = computed<EffectiveAttendanceEntry[]>(() => {
    this.attendanceFilterVersion();
    return this.buildMonthlyAttendanceEntries(this.selectedAttendanceStaffMemberId());
  });

  protected readonly attendanceSummary = computed<AttendanceSummary>(() =>
    this.buildAttendanceSummary(this.attendanceEntriesForSelectedStaff()),
  );

  protected readonly attendanceSummaryByStaff = computed<StaffAttendanceMonthRow[]>(() =>
    this.employeeStaffMembers()
      .map((staffMember) => ({
        staffMember,
        summary: this.buildAttendanceSummary(this.buildMonthlyAttendanceEntries(staffMember.id)),
        annualSummary: this.buildAttendanceSummary(this.buildYearlyAttendanceEntries(staffMember.id)),
      }))
      .filter(
        (row) =>
          row.staffMember.isActive ||
          row.summary.totalWorkedHours > 0 ||
          row.summary.vacationDays > 0 ||
          row.summary.permitDays > 0 ||
          row.summary.sickDays > 0 ||
          row.annualSummary.totalWorkedHours > 0 ||
          row.annualSummary.vacationDays > 0 ||
          row.annualSummary.permitDays > 0 ||
          row.annualSummary.sickDays > 0,
      )
      .sort((left, right) => left.staffMember.fullName.localeCompare(right.staffMember.fullName)),
  );

  protected readonly attendanceCalendarDays = computed(() => {
    this.attendanceFilterVersion();
    const year = Number.parseInt(this.attendanceFilter.year, 10);
    const monthIndex = Number.parseInt(this.attendanceFilter.month, 10) - 1;
    const firstDay = new Date(year, monthIndex, 1);
    const lastDay = new Date(year, monthIndex + 1, 0);
    const days: AttendanceCalendarDay[] = [];
    const selectedStaffMember = this.getAttendanceStaffMemberById(this.selectedAttendanceStaffMemberId());

    for (let day = 1; day <= lastDay.getDate(); day += 1) {
      const currentDate = new Date(year, monthIndex, day);
      const isoDate = this.toInputDate(currentDate);
      const weekdayKey = this.getWeekdayKeyFromDate(isoDate);
      const plannedShift = selectedStaffMember ? this.getPlannedShiftForDate(selectedStaffMember, isoDate) : null;
      const isNationalHoliday = this.isNationalHolidayDate(isoDate);
      days.push({
        isoDate,
        dayNumber: day,
        weekdayLabel: new Intl.DateTimeFormat(this.locale, { weekday: 'short' }).format(currentDate),
        isWeekend: weekdayKey === 'sabato' || weekdayKey === 'domenica',
        entry:
          this.attendanceEntriesForSelectedStaff().find((entry) => entry.entryDate === isoDate) ?? null,
        weekdayKey,
        isCompanyClosed: this.isCompanyClosureDate(isoDate),
        isNationalHoliday,
        plannedShift,
      });
    }

    return {
      monthStartWeekday: (firstDay.getDay() + 6) % 7,
      days,
    };
  });

  ngOnInit(): void {
    void this.initializeApp();
  }

  ngAfterViewChecked(): void {
    const nextRenderKey = this.getReportDetailChartsRenderKey();

    if (nextRenderKey === this.reportDetailChartsRenderKey) {
      return;
    }

    this.reportDetailChartsRenderKey = nextRenderKey;
    void this.renderReportDetailCharts();
  }

  ngOnDestroy(): void {
    window.clearInterval(this.currentDateTimerId);

    if (this.feedbackTimeoutId) {
      window.clearTimeout(this.feedbackTimeoutId);
    }

    if (this.remoteReloadTimeoutId) {
      window.clearTimeout(this.remoteReloadTimeoutId);
    }

    this.authSubscription?.unsubscribe();
    this.stopDataSync();
    this.destroyReportDetailCharts();
  }

  protected setAuthMode(mode: AuthMode): void {
    this.authMode.set(mode);
    this.authForm.password = '';
    this.authForm.confirmPassword = '';
    this.showAuthPassword.set(false);
    this.showAuthConfirmPassword.set(false);
  }

  protected toggleAuthPasswordVisibility(): void {
    this.showAuthPassword.update((value) => !value);
  }

  protected toggleAuthConfirmPasswordVisibility(): void {
    this.showAuthConfirmPassword.update((value) => !value);
  }

  protected async submitAuth(): Promise<void> {
    const email = this.authForm.email.trim().toLowerCase();
    const password = this.authForm.password;
    const confirmPassword = this.authForm.confirmPassword;

    if (!email) {
      this.setFeedback('error', 'Inserisci l\'email.');
      return;
    }

    if (!password) {
      this.setFeedback('error', 'Inserisci la password.');
      return;
    }

    if (this.authMode() === 'sign-up' && password !== confirmPassword) {
      this.setFeedback('error', 'Password e conferma password non coincidono.');
      return;
    }

    this.isAuthProcessing.set(true);

    try {
      if (this.authMode() === 'sign-up') {
        const result = await this.storeService.signUp(email, password);

        if (result.needsEmailConfirmation) {
          this.authForm.password = '';
          this.authForm.confirmPassword = '';
          this.authMode.set('sign-in');
          this.showAuthPassword.set(false);
          this.showAuthConfirmPassword.set(false);
          this.setFeedback('info', 'Account creato. Se non entri subito, controlla le impostazioni email di Supabase.');
          return;
        }

        this.showAuthPassword.set(false);
        this.showAuthConfirmPassword.set(false);
        this.setFeedback('success', 'Account creato e accesso effettuato.');
        return;
      }

      await this.storeService.signIn(email, password);
      this.authForm.password = '';
      this.authForm.confirmPassword = '';
      this.showAuthPassword.set(false);
      this.showAuthConfirmPassword.set(false);
      this.setFeedback('success', 'Accesso effettuato.');
    } catch (error) {
      this.setFeedback('error', this.getErrorMessage(error, 'Impossibile completare l\'accesso.'));
    } finally {
      this.isAuthProcessing.set(false);
    }
  }

  protected async logout(): Promise<void> {
    this.isAuthProcessing.set(true);

    try {
      await this.storeService.signOut();
      this.setFeedback('info', 'Logout effettuato.');
    } catch (error) {
      this.setFeedback('error', this.getErrorMessage(error, 'Impossibile completare il logout.'));
    } finally {
      this.isAuthProcessing.set(false);
    }
  }

  protected toggleSidebar(): void {
    this.isSidebarOpen.update((value) => !value);
  }

  protected closeSidebar(): void {
    this.isSidebarOpen.set(false);
  }

  protected openSection(section: AppSection): void {
    this.currentSection.set(section);
    this.closeSidebar();
  }

  protected async saveStaffMember(): Promise<void> {
    const fullName = this.staffForm.fullName.trim();
    const defaultDailyHours = this.normalizeAmount(this.staffForm.defaultDailyHours);
    const weeklySchedule = this.normalizeWeeklyScheduleForm(this.staffForm.weeklySchedule);

    if (!fullName) {
      this.setFeedback('error', 'Inserisci il nome della persona da registrare.');
      return;
    }

    if (defaultDailyHours < 0) {
      this.setFeedback('error', 'Le ore giornaliere non possono essere negative.');
      return;
    }

    const weeklyScheduleError = this.getWeeklyScheduleValidationError(weeklySchedule);

    if (weeklyScheduleError) {
      this.setFeedback('error', weeklyScheduleError);
      return;
    }

    const duplicateMember = this.staffMembers().find(
      (member) =>
        member.id !== this.editingStaffMemberId() && member.fullName.toLowerCase() === fullName.toLowerCase(),
    );

    if (duplicateMember) {
      this.setFeedback('error', 'Esiste gia un membro del personale con questo nome.');
      return;
    }

    if (
      this.staffForm.role === 'titolare' &&
      this.ownerCount(this.editingStaffMemberId()) >= 1
    ) {
      this.setFeedback('error', 'Puoi registrare una sola titolare.');
      return;
    }

    if (
      this.staffForm.role === 'dipendente' &&
      this.employeeCount(this.editingStaffMemberId()) >= 2
    ) {
      this.setFeedback('error', 'Hai indicato un massimo di due dipendenti.');
      return;
    }

    this.isSavingStaff.set(true);

    try {
      const editingStaffMemberId = this.editingStaffMemberId();

      if (editingStaffMemberId) {
        await this.storeService.updateStaffMemberSettings({
          staffMemberId: editingStaffMemberId,
          fullName,
          role: this.staffForm.role,
          defaultDailyHours,
          weeklySchedule,
        });
        this.staffMembers.update((members) =>
          members.map((member) =>
            member.id === editingStaffMemberId
              ? { ...member, fullName, role: this.staffForm.role, defaultDailyHours, weeklySchedule }
              : member,
          ),
        );
        this.setFeedback('success', 'Personale aggiornato correttamente.');
      } else {
        const createdStaffMember = await this.storeService.createStaffMember(
          fullName,
          this.staffForm.role,
          defaultDailyHours,
          weeklySchedule,
        );
        this.staffMembers.update((members) => [...members, createdStaffMember]);

        if (!this.saleForm.staffMemberId) {
          this.saleForm.staffMemberId = createdStaffMember.id;
        }

        if (!this.attendanceForm.staffMemberId && createdStaffMember.role === 'dipendente' && createdStaffMember.isActive) {
          this.attendanceForm.staffMemberId = createdStaffMember.id;
        }

        this.setFeedback('success', 'Personale registrato correttamente.');
      }

      this.resetStaffForm();
      this.ensureSelectedStaffMember();
      this.ensureSelectedAttendanceStaffMember();
    } finally {
      this.isSavingStaff.set(false);
    }
  }

  protected startEditStaffMember(staffMember: StaffMember): void {
    this.editingStaffMemberId.set(staffMember.id);
    this.staffForm.fullName = staffMember.fullName;
    this.staffForm.role = staffMember.role;
    this.staffForm.defaultDailyHours = staffMember.defaultDailyHours;
    this.staffForm.weeklySchedule = this.cloneWeeklySchedule(staffMember.weeklySchedule);
    this.currentSection.set('impostazioni');
  }

  protected cancelStaffEdit(): void {
    this.resetStaffForm();
  }

  protected async saveCompanySettings(): Promise<void> {
    this.isSavingSettings.set(true);

    try {
      await this.storeService.updateAppSettings(this.appSettings());
      this.staffMembers.update((members) =>
        members.map((member) => ({
          ...member,
          weeklySchedule: this.normalizeWeeklyScheduleForm(member.weeklySchedule),
        })),
      );
      this.setFeedback('success', 'Chiusure aziendali aggiornate.');
    } finally {
      this.isSavingSettings.set(false);
    }
  }

  protected toggleCompanyClosureDay(day: WeekdayKey): void {
    this.appSettings.update((settings) => {
      const daySet = new Set(settings.companyClosureDays);

      if (daySet.has(day)) {
        daySet.delete(day);
      } else {
        daySet.add(day);
      }

      return {
        companyClosureDays: [...daySet],
      };
    });

    this.staffForm.weeklySchedule = this.normalizeWeeklyScheduleForm(this.staffForm.weeklySchedule);
  }

  protected isCompanyClosureDay(day: WeekdayKey): boolean {
    return this.appSettings().companyClosureDays.includes(day);
  }

  protected toggleStaffWorkingDay(day: WeekdayKey): void {
    if (this.isCompanyClosureDay(day)) {
      return;
    }

    const currentDay = this.staffForm.weeklySchedule[day];
    this.staffForm.weeklySchedule = {
      ...this.staffForm.weeklySchedule,
      [day]: {
        isWorking: !currentDay.isWorking,
        hours: !currentDay.isWorking ? this.normalizeAmount(this.staffForm.defaultDailyHours) : 0,
      },
    };
  }

  protected updateStaffWorkingHours(day: WeekdayKey, hours: number): void {
    const normalizedHours = Math.max(0, this.normalizeAmount(hours));
    this.staffForm.weeklySchedule = {
      ...this.staffForm.weeklySchedule,
      [day]: {
        isWorking: !this.isCompanyClosureDay(day) && normalizedHours > 0,
        hours: this.isCompanyClosureDay(day) ? 0 : normalizedHours,
      },
    };
  }

  protected async hideOrDeleteStaffMember(staffMember: StaffMember): Promise<void> {
    if (this.hasStaffSales(staffMember.id)) {
      if (!window.confirm(`Nascondere ${staffMember.fullName}? Rimarra nei report storici ma non comparira piu in incasso.`)) {
        return;
      }

      await this.storeService.updateStaffMemberVisibility(staffMember.id, false);
      this.staffMembers.update((members) =>
        members.map((member) => (member.id === staffMember.id ? { ...member, isActive: false } : member)),
      );
      this.ensureSelectedStaffMember();
      this.setFeedback('info', 'Personale nascosto con successo.');
      return;
    }

    if (!window.confirm(`Eliminare ${staffMember.fullName}?`)) {
      return;
    }

    await this.storeService.deleteStaffMember(staffMember.id);
    this.staffMembers.update((members) => members.filter((member) => member.id !== staffMember.id));
    this.ensureSelectedStaffMember();
    this.setFeedback('info', 'Personale eliminato.');
  }

  protected async restoreStaffMember(staffMember: StaffMember): Promise<void> {
    if (staffMember.role === 'titolare' && this.ownerCount() >= 1) {
      this.setFeedback('error', 'Hai gia una titolare attiva.');
      return;
    }

    if (staffMember.role === 'dipendente' && this.employeeCount() >= 2) {
      this.setFeedback('error', 'Hai gia due dipendenti attivi.');
      return;
    }

    await this.storeService.updateStaffMemberVisibility(staffMember.id, true);
    this.staffMembers.update((members) =>
      members.map((member) => (member.id === staffMember.id ? { ...member, isActive: true } : member)),
    );
    this.ensureSelectedStaffMember();
    this.setFeedback('success', 'Personale riattivato.');
  }

  protected async addDailySale(): Promise<void> {
    if (!this.saleForm.staffMemberId) {
      this.setFeedback('error', 'Seleziona prima la titolare o una dipendente.');
      return;
    }

    if (!this.saleForm.saleDate) {
      this.setFeedback('error', 'Inserisci la data dell\'incasso.');
      return;
    }

    if (this.saleForm.regularAmount <= 0 && this.saleForm.testAmount <= 0) {
      this.setFeedback('error', 'Inserisci almeno un importo maggiore di zero.');
      return;
    }

    this.isSavingSale.set(true);

    try {
      const createdSale = await this.storeService.createDailySale({
        saleDate: this.saleForm.saleDate,
        staffMemberId: this.saleForm.staffMemberId,
        regularAmount: this.normalizeAmount(this.saleForm.regularAmount),
        testAmount: this.normalizeAmount(this.saleForm.testAmount),
        notes: this.saleForm.notes,
      });

      this.dailySales.update((sales) => [...sales, createdSale]);
      this.saleForm.regularAmount = 0;
      this.saleForm.testAmount = 0;
      this.saleForm.notes = '';
      this.setFeedback('success', 'Incasso giornaliero salvato.');
    } finally {
      this.isSavingSale.set(false);
    }
  }

  protected onAttendanceStaffChange(): void {
    const selectedStaffMember = this.staffMemberMap().get(this.attendanceForm.staffMemberId);

    if (!selectedStaffMember) {
      return;
    }

    const plannedShift = this.getPlannedShiftForDate(selectedStaffMember, this.attendanceForm.entryDate);
    this.attendanceForm.workedHours = plannedShift?.hours ?? 0;
  }

  protected selectAttendanceDay(isoDate: string): void {
    const selectedStaffMemberId = this.selectedAttendanceStaffMemberId();

    if (selectedStaffMemberId) {
      this.attendanceForm.staffMemberId = selectedStaffMemberId;
    }

    this.attendanceForm.entryDate = isoDate;
    this.attendanceForm.endDate = isoDate;

    const existingEntry = this.explicitAttendanceEntriesForSelectedStaff().find((entry) => entry.entryDate === isoDate);

    if (existingEntry) {
      this.startEditAttendanceEntry(existingEntry);
      this.isAttendanceModalOpen.set(true);
      return;
    }

    this.editingAttendanceEntryId.set(null);
    const selectedStaffMember = this.getSelectedAttendanceStaffMember();
    const plannedShift = selectedStaffMember ? this.getPlannedShiftForDate(selectedStaffMember, isoDate) : null;
    this.attendanceForm.entryType = !plannedShift || !plannedShift.isWorking ? 'festivo' : 'lavoro';
    this.attendanceForm.notes = '';
    this.attendanceForm.workedHours = plannedShift?.hours ?? 0;
    this.isAttendanceModalOpen.set(true);
  }

  protected onAttendanceFilterStaffChange(staffMemberId: string): void {
    this.attendanceFilter.staffMemberId = staffMemberId;
    this.selectedAttendanceStaffMemberId.set(staffMemberId);
    this.closeAttendanceModal();

    if (!staffMemberId) {
      this.attendanceFilterVersion.update((value) => value + 1);
      return;
    }

    this.attendanceForm.staffMemberId = staffMemberId;
    this.resetAttendanceForm();
    this.attendanceFilterVersion.update((value) => value + 1);
  }

  protected onAttendanceFilterPeriodChange(): void {
    this.attendanceFilterVersion.update((value) => value + 1);
    this.closeAttendanceModal();
  }

  protected closeAttendanceModal(): void {
    this.isAttendanceModalOpen.set(false);
  }

  protected isSelectedAttendanceStaffMember(staffMemberId: string): boolean {
    return this.selectedAttendanceStaffMemberId() === staffMemberId;
  }

  protected onAttendanceTypeChange(): void {
    const selectedStaffMember = this.staffMemberMap().get(this.attendanceForm.staffMemberId);

    if (!selectedStaffMember) {
      return;
    }

    if (this.attendanceForm.entryType === 'lavoro') {
      const plannedShift = this.getPlannedShiftForDate(selectedStaffMember, this.attendanceForm.entryDate);
      this.attendanceForm.workedHours = plannedShift?.hours ?? selectedStaffMember.defaultDailyHours;
      return;
    }

    if (this.attendanceForm.entryType === 'festivo') {
      this.attendanceForm.workedHours = 0;
      return;
    }

    if (this.attendanceForm.entryType === 'ferie' || this.attendanceForm.entryType === 'malattia') {
      this.attendanceForm.workedHours = 0;
      this.attendanceForm.endDate = this.attendanceForm.entryDate;
      return;
    }

    const plannedShift = this.getPlannedShiftForDate(selectedStaffMember, this.attendanceForm.entryDate);
    this.attendanceForm.workedHours = plannedShift?.hours ?? selectedStaffMember.defaultDailyHours;
  }

  protected async addAttendanceEntry(): Promise<void> {
    if (!this.attendanceForm.staffMemberId) {
      this.setFeedback('error', 'Seleziona un dipendente per registrare la presenza.');
      return;
    }

    if (!this.attendanceForm.entryDate) {
      this.setFeedback('error', 'Inserisci la data della presenza.');
      return;
    }

    if (this.attendanceForm.workedHours < 0) {
      this.setFeedback('error', 'Le ore non possono essere negative.');
      return;
    }

    if (this.attendanceForm.endDate < this.attendanceForm.entryDate) {
      this.setFeedback('error', 'La data finale non puo essere precedente alla data iniziale.');
      return;
    }

    if (this.attendanceForm.entryType === 'festivo' && this.attendanceForm.workedHours !== 0) {
      this.setFeedback('error', 'Per i giorni festivi le ore devono essere pari a zero.');
      return;
    }

    if (this.attendanceForm.entryType === 'lavoro' && this.attendanceForm.workedHours <= 0) {
      this.setFeedback('error', 'Per un giorno lavorativo inserisci ore maggiori di zero.');
      return;
    }

    const selectedStaffMember = this.getSelectedAttendanceStaffMember();

    if (!selectedStaffMember) {
      this.setFeedback('error', 'Seleziona un dipendente valido.');
      return;
    }

    const plannedShift = this.getPlannedShiftForDate(selectedStaffMember, this.attendanceForm.entryDate);

    if (this.attendanceForm.entryType === 'lavoro' && (!plannedShift || !plannedShift.isWorking)) {
      this.setFeedback('error', 'Non puoi inserire un turno lavorativo in un giorno non lavorativo o di chiusura.');
      return;
    }

    this.isSavingAttendance.set(true);

    try {
      const normalizedHours = this.normalizeAmount(this.attendanceForm.workedHours);
      const isRangeEntry =
        this.attendanceForm.entryType === 'ferie' || this.attendanceForm.entryType === 'malattia';
      const targetDates = this.getAttendanceTargetDates(
        this.attendanceForm.entryType,
        this.attendanceForm.entryDate,
        this.attendanceForm.endDate,
      );

      if (isRangeEntry && targetDates.length === 0) {
        this.setFeedback('error', 'Nel periodo selezionato non ci sono giorni validi da registrare.');
        return;
      }

      const editingEntryIds = this.editingAttendanceEntryIds();
      const conflictingEntry = this.findConflictingExplicitEntry(targetDates, editingEntryIds);

      if (conflictingEntry) {
        this.setFeedback('error', `Esiste gia una presenza registrata il ${this.formatDate(conflictingEntry.entryDate)}.`);
        return;
      }

      if (this.editingAttendanceEntryId()) {
        const attendanceEntryId = this.editingAttendanceEntryId();

        if (!attendanceEntryId) {
          return;
        }

        const currentEntry = this.attendanceEntries().find((entry) => entry.id === attendanceEntryId);
        const editingEntries = this.attendanceEntries().filter((entry) => editingEntryIds.includes(entry.id));

        if (
          !currentEntry ||
          editingEntries.length === 0 ||
          editingEntries.some((entry) => !this.canEditAttendanceEntry(entry))
        ) {
          this.setFeedback('error', 'La presenza non e piu modificabile.');
          return;
        }

        const shouldRecreateEntries =
          editingEntries.length > 1 ||
          currentEntry.entryType === 'ferie' ||
          currentEntry.entryType === 'malattia' ||
          this.attendanceForm.entryType === 'ferie' ||
          this.attendanceForm.entryType === 'malattia';

        if (!shouldRecreateEntries) {
          await this.storeService.updateAttendanceEntry({
            attendanceEntryId,
            staffMemberId: this.attendanceForm.staffMemberId,
            entryDate: this.attendanceForm.entryDate,
            entryType: this.attendanceForm.entryType,
            workedHours: normalizedHours,
            notes: this.attendanceForm.notes,
          });

          this.attendanceEntries.update((entries) =>
            entries.map((entry) =>
              entry.id === attendanceEntryId
                ? {
                    ...entry,
                    staffMemberId: this.attendanceForm.staffMemberId,
                    entryDate: this.attendanceForm.entryDate,
                    entryType: this.attendanceForm.entryType,
                    workedHours: normalizedHours,
                    notes: this.attendanceForm.notes.trim(),
                  }
                : entry,
            ),
          );
        } else {
          for (const entry of editingEntries) {
            await this.storeService.deleteAttendanceEntry(entry.id);
          }

          const recreatedEntries = await this.createAttendanceEntriesForDates(targetDates, normalizedHours);
          this.attendanceEntries.update((entries) => [
            ...entries.filter((entry) => !editingEntryIds.includes(entry.id)),
            ...recreatedEntries,
          ]);
        }

        this.setFeedback('success', 'Presenza aggiornata correttamente.');
      } else {
        const createdEntries = await this.createAttendanceEntriesForDates(targetDates, normalizedHours);

        this.attendanceEntries.update((entries) => [...entries, ...createdEntries]);
        this.attendanceFilter.staffMemberId = this.attendanceForm.staffMemberId;
        this.selectedAttendanceStaffMemberId.set(this.attendanceForm.staffMemberId);
        this.attendanceFilter.month = this.attendanceForm.entryDate.slice(5, 7);
        this.attendanceFilter.year = this.attendanceForm.entryDate.slice(0, 4);
        this.setFeedback(
          'success',
          isRangeEntry
            ? `${this.getAttendanceTypeLabel(this.attendanceForm.entryType)} registrata dal ${this.formatDate(this.attendanceForm.entryDate)} al ${this.formatDate(this.attendanceForm.endDate)}.`
            : 'Presenza registrata correttamente.',
        );
      }

      this.resetAttendanceForm();
      this.isAttendanceModalOpen.set(false);
    } finally {
      this.isSavingAttendance.set(false);
    }
  }

  protected startEditAttendanceEntry(entry: AttendanceEntry): void {
    const editingEntries = this.getAttendanceEditEntries(entry);
    const orderedEditingEntries = [...editingEntries].sort((left, right) => left.entryDate.localeCompare(right.entryDate));
    const firstEntry = orderedEditingEntries[0] ?? entry;
    const lastEntry = orderedEditingEntries.at(-1) ?? entry;

    this.editingAttendanceEntryId.set(entry.id);
    this.editingAttendanceEntryIds.set(orderedEditingEntries.map((editingEntry) => editingEntry.id));
    this.attendanceForm.staffMemberId = entry.staffMemberId;
    this.attendanceForm.entryDate = firstEntry.entryDate;
    this.attendanceForm.endDate = lastEntry.entryDate;
    this.attendanceForm.entryType = entry.entryType;
    this.attendanceForm.workedHours = entry.workedHours;
    this.attendanceForm.notes = entry.notes;
  }

  protected cancelAttendanceEdit(): void {
    this.resetAttendanceForm();
    this.isAttendanceModalOpen.set(false);
  }

  protected canEditAttendanceEntry(entry: AttendanceEntry): boolean {
    const today = new Date(this.today());
    const entryDate = new Date(entry.entryDate);
    const differenceMs = today.getTime() - entryDate.getTime();
    const differenceDays = differenceMs / (1000 * 60 * 60 * 24);
    return differenceDays <= this.attendanceEditWindowDays;
  }

  protected async deleteAttendanceEntry(entry: AttendanceEntry): Promise<void> {
    if (!this.canEditAttendanceEntry(entry)) {
      this.setFeedback('error', 'La presenza non puo piu essere corretta o eliminata.');
      return;
    }

    if (!window.confirm('Eliminare questa presenza?')) {
      return;
    }

    await this.storeService.deleteAttendanceEntry(entry.id);
    this.attendanceEntries.update((entries) => entries.filter((currentEntry) => currentEntry.id !== entry.id));
    this.setFeedback('info', 'Presenza eliminata.');
    this.isAttendanceModalOpen.set(false);
  }

  protected async deleteDailySale(sale: DailySale): Promise<void> {
    if (!window.confirm('Eliminare questo incasso giornaliero?')) {
      return;
    }

    await this.storeService.deleteDailySale(sale.id);
    this.dailySales.update((sales) => sales.filter((currentSale) => currentSale.id !== sale.id));
    this.setFeedback('info', 'Incasso eliminato.');
  }

  protected async exportPdf(staffMember?: StaffMember): Promise<void> {
    const sales = staffMember
      ? this.getSalesForStaffInCurrentReport(staffMember.id)
      : this.filteredReportSales();

    if (sales.length === 0) {
      this.setFeedback('error', 'Non ci sono incassi nel periodo selezionato per generare il PDF.');
      return;
    }

    const [{ default: jsPDF }, { default: autoTable }] = await Promise.all([
      import('jspdf'),
      import('jspdf-autotable'),
    ]);

    const document = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4',
    });

    document.setFontSize(18);
    document.text(
      staffMember ? `Report ${staffMember.fullName}` : 'Report incassi Goldfinger Manager',
      14,
      18,
    );
    document.setFontSize(11);
    document.text(`Periodo: ${this.reportPeriodLabel()}`, 14, 26);

    autoTable(document, {
      startY: 34,
      head: [['Data', 'Persona', 'Regolare', 'Test', 'Totale', 'Note']],
      body: sales.map((sale) => [
        this.formatDate(sale.saleDate),
        this.staffMemberMap().get(sale.staffMemberId)?.fullName ?? 'Non assegnato',
        this.formatCurrency(sale.regularAmount),
        this.formatCurrency(sale.testAmount),
        this.formatCurrency(sale.regularAmount + sale.testAmount),
        sale.notes || '-',
      ]),
      styles: {
        fontSize: 9,
        cellPadding: 2,
      },
      headStyles: {
        fillColor: [31, 41, 55],
      },
    });

    const totals = sales.reduce(
      (accumulator, sale) => {
        accumulator.regular += sale.regularAmount;
        accumulator.test += sale.testAmount;
        return accumulator;
      },
      { regular: 0, test: 0 },
    );

    const finalY = (document as typeof document & { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY ?? 34;
    document.setFontSize(11);
    document.text(`Totale regolare: ${this.formatCurrency(totals.regular)}`, 14, finalY + 12);
    document.text(`Totale test: ${this.formatCurrency(totals.test)}`, 14, finalY + 19);
    document.text(`Totale complessivo: ${this.formatCurrency(totals.regular + totals.test)}`, 14, finalY + 26);
    await this.savePdfDocument(
      document,
      staffMember
        ? `report-incassi-${staffMember.fullName.toLowerCase().replaceAll(' ', '-')}-${this.reportFilter.year}-${this.reportFilter.month}.pdf`
        : `report-incassi-${this.reportFilter.year}-${this.reportFilter.month}.pdf`,
    );

    this.setFeedback(
      'success',
      staffMember ? `PDF generato per ${staffMember.fullName}.` : 'PDF generato correttamente.',
    );
  }

  protected async exportAttendancePdf(): Promise<void> {
    const rows = this.attendanceSummaryByStaff();

    if (rows.length === 0) {
      this.setFeedback('error', 'Non ci sono dipendenti da esportare nel mese selezionato.');
      return;
    }

    const year = Number.parseInt(this.attendanceFilter.year, 10);
    const monthIndex = Number.parseInt(this.attendanceFilter.month, 10) - 1;
    const daysInMonth = new Date(year, monthIndex + 1, 0).getDate();
    const dayHeaders = Array.from({ length: daysInMonth }, (_, index) => String(index + 1));
    const pageWidth = 297;
    const marginLeft = 8;
    const marginRight = 8;
    const availableTableWidth = pageWidth - marginLeft - marginRight;
    const staffColumnWidth = 56;
    const totalColumnWidth = 14;
    const dayCellWidth = Math.max(
      6.8,
      (availableTableWidth - staffColumnWidth - totalColumnWidth) / daysInMonth,
    );

    const [{ default: jsPDF }, { default: autoTable }] = await Promise.all([
      import('jspdf'),
      import('jspdf-autotable'),
    ]);

    const document = new jsPDF({
      orientation: 'landscape',
      unit: 'mm',
      format: 'a4',
    });

    document.setFontSize(18);
    document.text('Registro Presenze Mensile', 12, 14);
    document.setFontSize(12);
    document.text(`Periodo: ${this.attendancePeriodLabel()}`, 12, 22);
    document.text('Legenda: numero=ore lavorate/permesso, F=ferie, M=malattia, C=chiuso/festivo', 12, 29);

    const tableHead = [['Dipendente', ...dayHeaders, 'Tot']];
    const tableBody = rows.map(({ staffMember }) => {
      const entriesMap = new Map(
        this.buildMonthlyAttendanceEntries(staffMember.id).map((entry) => [entry.entryDate, entry]),
      );
      const dayCells: string[] = [];
      let workedHoursTotal = 0;

      for (let day = 1; day <= daysInMonth; day += 1) {
        const isoDate = this.toInputDate(new Date(year, monthIndex, day));
        const entry = entriesMap.get(isoDate);

        if (entry) {
          if (entry.entryType === 'ferie') {
            dayCells.push('F');
          } else if (entry.entryType === 'malattia') {
            dayCells.push('M');
          } else if (entry.entryType === 'festivo') {
            dayCells.push('C');
          } else {
            dayCells.push(this.formatCompactHours(entry.workedHours));
            workedHoursTotal += entry.workedHours;
          }
          continue;
        }

        if (this.isHolidayDate(isoDate)) {
          dayCells.push('C');
          continue;
        }

        dayCells.push('-');
      }

      return [staffMember.fullName, ...dayCells, this.formatCompactHours(workedHoursTotal)];
    });

    autoTable(document, {
      startY: 33,
      head: tableHead,
      body: tableBody,
      styles: {
        fontSize: 8.2,
        cellPadding: 1.6,
        halign: 'center',
        valign: 'middle',
        lineColor: [229, 231, 235],
        lineWidth: 0.1,
      },
      headStyles: {
        fillColor: [31, 41, 55],
        textColor: 255,
        fontSize: 8.5,
      },
      columnStyles: {
        0: { cellWidth: staffColumnWidth, halign: 'left' },
        [daysInMonth + 1]: { cellWidth: totalColumnWidth, halign: 'right' },
      },
      tableWidth: 'auto',
      margin: { left: marginLeft, right: marginRight },
      didParseCell: (hookData) => {
        if (hookData.column.index > 0 && hookData.column.index <= daysInMonth) {
          hookData.cell.styles.cellWidth = dayCellWidth;
        }
      },
    });

    await this.savePdfDocument(document, `presenze-mensili-${this.attendanceFilter.year}-${this.attendanceFilter.month}.pdf`);

    this.setFeedback('success', 'PDF mensile presenze generato correttamente.');
  }

  protected async exportDetailedReportPdf(): Promise<void> {
    const selectedStaffMember = this.selectedReportStaffMember();

    if (!selectedStaffMember) {
      this.setFeedback('error', 'Seleziona prima una persona dal riepilogo andamento.');
      return;
    }

    if (!this.reportDetailHasData()) {
      this.setFeedback('error', 'Non ci sono dati nel periodo selezionato per generare il report dettagliato.');
      return;
    }

    await this.renderReportDetailCharts();

    const [{ default: jsPDF }, { default: autoTable }] = await Promise.all([
      import('jspdf'),
      import('jspdf-autotable'),
    ]);
    const document = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4',
    });
    const metrics = this.reportDetailMetrics();
    const monthlyRows = this.reportDetailMonthlyRows();
    const dailyRows = this.reportDetailDailyRows();
    const attendanceRows = this.reportDetailAttendanceRows();
    const timestamp = new Intl.DateTimeFormat(this.locale, {
      dateStyle: 'short',
      timeStyle: 'medium',
    }).format(new Date());
    const signature = await this.generateReportSignature(
      JSON.stringify({
        staffMemberId: selectedStaffMember.id,
        startDate: this.reportDetailFilter.startDate,
        endDate: this.reportDetailFilter.endDate,
        totalAmount: metrics.totalAmount,
        workedDays: metrics.workedDays,
        absenceDays: metrics.absenceDays,
      }),
    );

    document.setFontSize(18);
    document.text(`Report avanzato ${selectedStaffMember.fullName}`, 14, 18);
    document.setFontSize(11);
    document.text(`Azienda: ${this.title}`, 14, 26);
    document.text(`Periodo: ${this.reportDetailPeriodLabel()}`, 14, 32);
    document.text(`Profilo: ${this.getRoleLabel(selectedStaffMember.role)}`, 14, 38);
    document.text(`Generato il: ${timestamp}`, 14, 44);

    autoTable(document, {
      startY: 50,
      head: [['Indicatore', 'Valore']],
      body: [
        ['Totale incassi', this.formatCurrency(metrics.totalAmount)],
        ['Incasso regolare', this.formatCurrency(metrics.totalRegular)],
        ['Incasso test', this.formatCurrency(metrics.totalTest)],
        ['Media giornaliera', this.formatCurrency(metrics.averageDaily)],
        ['Giorni lavorati', String(metrics.workedDays)],
        ['Giorni lavorabili pianificati', String(metrics.plannedWorkingDays)],
        ['Assenze', String(metrics.absenceDays)],
        ['Indice di produttivita', this.formatProductivityIndex(metrics.productivityIndex)],
        ['Ferie maturate stimate', this.formatCompactHours(metrics.vacationAccrued)],
        ['Ferie utilizzate', String(metrics.vacationUsed)],
        ['Permessi', String(metrics.permitDays)],
        ['Malattia', String(metrics.sickDays)],
      ],
      styles: {
        fontSize: 9.2,
        cellPadding: 2.4,
      },
      headStyles: {
        fillColor: [37, 99, 235],
      },
      alternateRowStyles: {
        fillColor: [248, 250, 252],
      },
    });

    document.addPage();
    document.setFontSize(16);
    document.text('Storico incassi e grafici', 14, 18);
    const monthlyChartImage = this.getReportChartImageData('report-monthly-chart');
    const dailyChartImage = this.getReportChartImageData('report-daily-chart');
    const distributionChartImage = this.getReportChartImageData('report-distribution-chart');

    if (monthlyChartImage) {
      document.setFontSize(11);
      document.text('Incassi mensili', 14, 28);
      document.addImage(monthlyChartImage, 'PNG', 14, 32, 182, 58);
    }

    if (dailyChartImage) {
      document.setFontSize(11);
      document.text('Andamento giornaliero', 14, 100);
      document.addImage(dailyChartImage, 'PNG', 14, 104, 182, 58);
    }

    if (distributionChartImage) {
      document.setFontSize(11);
      document.text('Distribuzione presenze, ferie e malattie', 14, 172);
      document.addImage(distributionChartImage, 'PNG', 14, 176, 84, 84);
    }

    document.addPage();
    document.setFontSize(16);
    document.text('Tabelle di dettaglio', 14, 18);

    autoTable(document, {
      startY: 24,
      head: [['Mese', 'Totale', 'Regolare', 'Test', 'Giorni', 'Media']],
      body: monthlyRows.map((row) => [
        row.label,
        this.formatCurrency(row.totalAmount),
        this.formatCurrency(row.regularAmount),
        this.formatCurrency(row.testAmount),
        String(row.workedDays),
        this.formatCurrency(row.averageDaily),
      ]),
      styles: {
        fontSize: 8.5,
        cellPadding: 2,
      },
      headStyles: {
        fillColor: [17, 24, 39],
      },
    });

    autoTable(document, {
      startY: ((document as typeof document & { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY ?? 24) + 10,
      head: [['Data', 'Totale', 'Regolare', 'Test']],
      body: dailyRows.map((row) => [
        row.label,
        this.formatCurrency(row.totalAmount),
        this.formatCurrency(row.regularAmount),
        this.formatCurrency(row.testAmount),
      ]),
      styles: {
        fontSize: 8.3,
        cellPadding: 2,
      },
      headStyles: {
        fillColor: [37, 99, 235],
      },
    });

    document.addPage();
    document.setFontSize(16);
    document.text('Presenze giornaliere', 14, 18);

    autoTable(document, {
      startY: 24,
      head: [['Data', 'Voce', 'Ore', 'Origine', 'Note']],
      body: attendanceRows.map((row) => [
        row.label,
        row.typeLabel,
        this.formatCompactHours(row.workedHours),
        row.sourceLabel,
        row.notes,
      ]),
      styles: {
        fontSize: 8.2,
        cellPadding: 2,
      },
      headStyles: {
        fillColor: [5, 150, 105],
      },
    });

    const finalY =
      ((document as typeof document & { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY ?? 24) + 12;
    document.setFontSize(10);
    document.text(`Firma digitale: ${signature}`, 14, Math.min(finalY, 272));

    this.decorateReportPdfPages(
      document,
      `${selectedStaffMember.fullName} · ${this.reportDetailPeriodLabel()}`,
      timestamp,
      signature,
    );

    await this.savePdfDocument(
      document,
      `report-dettagliato-${selectedStaffMember.fullName.toLowerCase().replaceAll(' ', '-')}-${this.reportDetailFilter.startDate}-${this.reportDetailFilter.endDate}.pdf`,
    );

    this.setFeedback('success', `PDF dettagliato generato per ${selectedStaffMember.fullName}.`);
  }

  protected getStaffLabel(staffMemberId: string): string {
    return this.staffMemberMap().get(staffMemberId)?.fullName ?? 'Non assegnato';
  }

  protected getRoleLabel(role: PersonRole): string {
    return role === 'titolare' ? 'Titolare' : 'Dipendente';
  }

  protected getStaffActionLabel(staffMember: StaffMember): string {
    return this.hasStaffSales(staffMember.id) ? 'Nascondi' : 'Elimina';
  }

  protected hasStaffSales(staffMemberId: string): boolean {
    return this.dailySales().some((sale) => sale.staffMemberId === staffMemberId);
  }

  protected getBarWidth(totalAmount: number): string {
    const maxTotal = this.reportMaxTotal();

    if (!maxTotal) {
      return '0%';
    }

    return `${Math.max((totalAmount / maxTotal) * 100, 8)}%`;
  }

  protected trackByStaffMember(_: number, staffMember: StaffMember): string {
    return staffMember.id;
  }

  protected trackBySale(_: number, sale: DailySale): string {
    return sale.id;
  }

  protected trackByAttendance(_: number, entry: AttendanceEntry): string {
    return entry.id;
  }

  protected trackBySection(_: number, item: { id: AppSection }): string {
    return item.id;
  }

  private async initializeApp(): Promise<void> {
    this.authSubscription = this.storeService.onAuthStateChange((session) => {
      void this.syncAuthSession(session);
    });

    try {
      const session = await this.storeService.getSession();
      await this.syncAuthSession(session);
    } catch (error) {
      this.isLoading.set(false);
      this.isAuthReady.set(true);
      this.setFeedback('error', this.getErrorMessage(error, 'Impossibile avviare il login.'));
    }
  }

  private async syncAuthSession(session: Session | null): Promise<void> {
    this.authSession.set(session);
    this.isAuthReady.set(true);

    if (!session) {
      this.loadedUserId = null;
      this.loadingUserId = null;
      this.stopDataSync();
      this.clearDataState();
      this.isLoading.set(false);
      return;
    }

    if (this.loadedUserId === session.user.id || this.loadingUserId === session.user.id) {
      await this.ensureDataSync(session.user.id);
      return;
    }

    this.loadingUserId = session.user.id;

    try {
      await this.loadData();
      this.loadedUserId = session.user.id;
      await this.ensureDataSync(session.user.id);
    } finally {
      if (this.loadingUserId === session.user.id) {
        this.loadingUserId = null;
      }
    }
  }

  private async ensureDataSync(userId: string): Promise<void> {
    if (this.dataSyncUserId === userId && this.dataSyncSubscription) {
      return;
    }

    this.stopDataSync();
    this.dataSyncSubscription = await this.storeService.subscribeToDataChanges(() => {
      this.scheduleRemoteReload(userId);
    });
    this.dataSyncUserId = userId;
  }

  private async loadData(): Promise<void> {
    this.isLoading.set(true);

    try {
      const [appSettings, staffMembers, dailySales, attendanceEntries] = await Promise.all([
        this.storeService.getAppSettings(),
        this.storeService.getStaffMembers(),
        this.storeService.getDailySales(),
        this.storeService.getAttendanceEntries(),
      ]);

      this.appSettings.set(appSettings);
      this.staffMembers.set(staffMembers);
      this.dailySales.set(dailySales);
      this.attendanceEntries.set(attendanceEntries);
      if (this.selectedReportStaffMemberId() && !staffMembers.some((staffMember) => staffMember.id === this.selectedReportStaffMemberId())) {
        this.selectedReportStaffMemberId.set(null);
      }
      this.ensureSelectedStaffMember();
      this.ensureSelectedAttendanceStaffMember();
    } finally {
      this.isLoading.set(false);
    }
  }

  private clearDataState(): void {
    this.currentSection.set('dashboard');
    this.isSidebarOpen.set(false);
    this.appSettings.set({ companyClosureDays: ['domenica'] });
    this.staffMembers.set([]);
    this.dailySales.set([]);
    this.attendanceEntries.set([]);
    this.editingStaffMemberId.set(null);
    this.editingAttendanceEntryId.set(null);
    this.resetStaffForm();
    this.saleForm.saleDate = this.today();
    this.saleForm.staffMemberId = '';
    this.saleForm.regularAmount = 0;
    this.saleForm.testAmount = 0;
    this.saleForm.notes = '';
    this.resetAttendanceForm();
    this.attendanceFilter.staffMemberId = '';
    this.selectedAttendanceStaffMemberId.set('');
    this.selectedReportStaffMemberId.set(null);
    this.attendanceFilter.month = this.today().slice(5, 7);
    this.attendanceFilter.year = String(new Date().getFullYear());
  }

  private stopDataSync(): void {
    if (this.remoteReloadTimeoutId) {
      window.clearTimeout(this.remoteReloadTimeoutId);
      this.remoteReloadTimeoutId = null;
    }

    this.dataSyncSubscription?.unsubscribe();
    this.dataSyncSubscription = null;
    this.dataSyncUserId = null;
  }

  private scheduleRemoteReload(userId: string): void {
    if (this.authSession()?.user.id !== userId) {
      return;
    }

    if (this.remoteReloadTimeoutId) {
      window.clearTimeout(this.remoteReloadTimeoutId);
    }

    this.remoteReloadTimeoutId = window.setTimeout(() => {
      this.remoteReloadTimeoutId = null;
      void this.reloadRemoteData(userId);
    }, 250);
  }

  private async reloadRemoteData(userId: string): Promise<void> {
    if (this.loadingUserId || this.authSession()?.user.id !== userId) {
      return;
    }

    try {
      await this.loadData();
      this.loadedUserId = userId;
    } catch (error) {
      console.error('Errore durante la sincronizzazione dei dati.', error);
    }
  }

  private filterSalesByDateRange(sales: DailySale[], startDate: string, endDate: string): DailySale[] {
    if (!startDate || !endDate) {
      return sales;
    }

    const normalizedEndDate = endDate < startDate ? startDate : endDate;

    return sales.filter((sale) => sale.saleDate >= startDate && sale.saleDate <= normalizedEndDate);
  }

  private filterAttendanceByMonth(entries: AttendanceEntry[], month: string, year: string): AttendanceEntry[] {
    return [...entries]
      .filter((entry) => entry.entryDate.startsWith(`${year}-${month}`))
      .sort((left, right) => right.entryDate.localeCompare(left.entryDate));
  }

  private getMonthDateRange(year: string, month: string): { startDate: string; endDate: string } {
    const yearNumber = Number.parseInt(year, 10);
    const monthIndex = Number.parseInt(month, 10) - 1;

    return {
      startDate: `${year}-${month}-01`,
      endDate: this.toInputDate(new Date(yearNumber, monthIndex + 1, 0)),
    };
  }

  private isWholeSelectedMonthRange(): boolean {
    const { startDate, endDate } = this.getMonthDateRange(this.reportFilter.year, this.reportFilter.month);
    return this.reportFilter.startDate === startDate && this.reportFilter.endDate === endDate;
  }

  private getSalesForStaffInCurrentReport(staffMemberId: string): DailySale[] {
    return this.filteredReportSales().filter((sale) => sale.staffMemberId === staffMemberId);
  }

  private getSalesForStaffInRange(staffMemberId: string, startDate: string, endDate: string): DailySale[] {
    return this.dailySales()
      .filter((sale) => sale.staffMemberId === staffMemberId)
      .filter((sale) => sale.saleDate >= startDate && sale.saleDate <= endDate);
  }

  private sumSalesAmount(sales: DailySale[]): number {
    return sales.reduce((total, sale) => total + sale.regularAmount + sale.testAmount, 0);
  }

  private calculateTrendPercentage(currentValue: number, previousValue: number): number | null {
    if (previousValue === 0) {
      return currentValue > 0 ? null : 0;
    }

    return ((currentValue - previousValue) / previousValue) * 100;
  }

  private getMonthDateRangeFromIsoDate(isoDate: string): { startDate: string; endDate: string } {
    return this.getMonthDateRange(isoDate.slice(0, 4), isoDate.slice(5, 7));
  }

  private getPlannedWorkingDaysInRange(staffMember: StaffMember, startDate: string, endDate: string): number {
    const employeeStartDate = staffMember.createdAt.slice(0, 10);
    const effectiveEndDate = endDate > this.today() ? this.today() : endDate;

    return this.getDateRange(startDate, effectiveEndDate).filter((isoDate) => {
      if (isoDate < employeeStartDate) {
        return false;
      }

      return this.getPlannedShiftForDate(staffMember, isoDate).isWorking;
    }).length;
  }

  private calculateVacationAccrual(staffMember: StaffMember, startDate: string, endDate: string): number {
    const employeeStartDate = staffMember.createdAt.slice(0, 10);
    const effectiveStartDate = employeeStartDate > startDate ? employeeStartDate : startDate;
    const effectiveEndDate = endDate > this.today() ? this.today() : endDate;

    if (effectiveEndDate < effectiveStartDate) {
      return 0;
    }

    const activeMonths = new Set(this.getDateRange(effectiveStartDate, effectiveEndDate).map((date) => date.slice(0, 7)));
    return this.normalizeAmount(activeMonths.size * 2.17);
  }

  private ownerCount(excludedStaffMemberId?: string | null): number {
    return this.activeStaffMembers().filter(
      (member) => member.role === 'titolare' && member.id !== excludedStaffMemberId,
    ).length;
  }

  private employeeCount(excludedStaffMemberId?: string | null): number {
    return this.activeStaffMembers().filter(
      (member) => member.role === 'dipendente' && member.id !== excludedStaffMemberId,
    ).length;
  }

  private normalizeAmount(amount: number): number {
    return Math.round(amount * 100) / 100;
  }

  private toInputDate(date: Date): string {
    const year = date.getFullYear();
    const month = String(date.getMonth() + 1).padStart(2, '0');
    const day = String(date.getDate()).padStart(2, '0');
    return `${year}-${month}-${day}`;
  }

  private formatCurrency(amount: number): string {
    return new Intl.NumberFormat(this.locale, {
      style: 'currency',
      currency: this.currencyCode,
      minimumFractionDigits: 2,
    }).format(amount);
  }

  private formatDate(date: string): string {
    return new Intl.DateTimeFormat(this.locale).format(new Date(date));
  }

  private async savePdfDocument(
    document: { save: (filename: string) => void; output: (type: 'blob') => Blob },
    fileName: string,
  ): Promise<void> {
    if (!this.isIphoneOrIpad()) {
      document.save(fileName);
      return;
    }

    const pdfBlob = document.output('blob');
    const pdfFile = new File([pdfBlob], fileName, { type: 'application/pdf' });

    if (navigator.share && navigator.canShare?.({ files: [pdfFile] })) {
      try {
        await navigator.share({
          files: [pdfFile],
          title: fileName,
        });
      } catch (error) {
        if (error instanceof DOMException && error.name === 'AbortError') {
          return;
        }
      }
      return;
    }

    const blobUrl = URL.createObjectURL(pdfBlob);
    const popupWindow = window.open(blobUrl, '_blank', 'noopener,noreferrer');

    if (!popupWindow) {
      const downloadLink = window.document.createElement('a');
      downloadLink.href = blobUrl;
      downloadLink.target = '_blank';
      downloadLink.rel = 'noopener noreferrer';
      downloadLink.click();
    }

    window.setTimeout(() => {
      URL.revokeObjectURL(blobUrl);
    }, 60_000);
  }

  private getReportDetailChartsRenderKey(): string {
    if (this.currentSection() !== 'report' || !this.selectedReportStaffMember()) {
      return '';
    }

    return JSON.stringify({
      staffMemberId: this.selectedReportStaffMemberId(),
      startDate: this.reportDetailFilter.startDate,
      endDate: this.reportDetailFilter.endDate,
      monthlyRows: this.reportDetailMonthlyRows().map((row) => [row.monthKey, row.totalAmount]),
      dailyRows: this.reportDetailDailyRows().map((row) => [row.isoDate, row.totalAmount]),
      distribution: this.reportDetailDistribution().map((slice) => slice.value),
    });
  }

  private async loadReportChartLibrary(): Promise<typeof import('chart.js/auto')> {
    if (!this.reportChartLibraryPromise) {
      this.reportChartLibraryPromise = import('chart.js/auto');
    }

    return this.reportChartLibraryPromise;
  }

  private async renderReportDetailCharts(): Promise<void> {
    const renderKey = this.getReportDetailChartsRenderKey();

    if (!renderKey) {
      this.destroyReportDetailCharts();
      return;
    }

    const monthlyCanvas = document.getElementById('report-monthly-chart') as HTMLCanvasElement | null;
    const dailyCanvas = document.getElementById('report-daily-chart') as HTMLCanvasElement | null;
    const distributionCanvas = document.getElementById('report-distribution-chart') as HTMLCanvasElement | null;

    if (!monthlyCanvas || !dailyCanvas || !distributionCanvas) {
      return;
    }

    const { default: Chart } = await this.loadReportChartLibrary();
    this.destroyReportDetailCharts();

    const monthlyRows = this.reportDetailMonthlyRows();
    const dailyRows = this.reportDetailDailyRows();
    const distributionRows = this.reportDetailDistribution();
    const distributionHasValues = distributionRows.some((slice) => slice.value > 0);

    this.reportChartInstances.set(
      'monthly',
      new Chart(monthlyCanvas, {
        type: 'bar',
        data: {
          labels: monthlyRows.length ? monthlyRows.map((row) => row.label) : ['Nessun dato'],
          datasets: [
            {
              label: 'Incassi mensili',
              data: monthlyRows.length ? monthlyRows.map((row) => row.totalAmount) : [0],
              backgroundColor: 'rgba(37, 99, 235, 0.82)',
              borderRadius: 10,
            },
          ],
        },
        options: {
          responsive: true,
          maintainAspectRatio: false,
          plugins: {
            legend: {
              display: false,
            },
            tooltip: {
              callbacks: {
                label: (context) => this.formatCurrency(Number(context.raw ?? 0)),
              },
            },
          },
          scales: {
            y: {
              beginAtZero: true,
              ticks: {
                callback: (value) => this.formatCurrency(Number(value)),
              },
            },
          },
        },
      }),
    );

    this.reportChartInstances.set(
      'daily',
      new Chart(dailyCanvas, {
        type: 'line',
        data: {
          labels: dailyRows.length ? dailyRows.map((row) => row.label) : ['Nessun dato'],
          datasets: [
            {
              label: 'Incasso giornaliero',
              data: dailyRows.length ? dailyRows.map((row) => row.totalAmount) : [0],
              borderColor: '#8b5cf6',
              backgroundColor: 'rgba(139, 92, 246, 0.18)',
              fill: true,
              tension: 0.28,
              pointRadius: 3,
              pointHoverRadius: 5,
            },
          ],
        },
        options: {
          responsive: true,
          maintainAspectRatio: false,
          interaction: {
            mode: 'index',
            intersect: false,
          },
          plugins: {
            legend: {
              display: false,
            },
            tooltip: {
              callbacks: {
                label: (context) => this.formatCurrency(Number(context.raw ?? 0)),
              },
            },
          },
          scales: {
            y: {
              beginAtZero: true,
              ticks: {
                callback: (value) => this.formatCurrency(Number(value)),
              },
            },
          },
        },
      }),
    );

    this.reportChartInstances.set(
      'distribution',
      new Chart(distributionCanvas, {
        type: 'pie',
        data: {
          labels: distributionHasValues ? distributionRows.map((slice) => slice.label) : ['Nessun dato'],
          datasets: [
            {
              label: 'Distribuzione presenze',
              data: distributionHasValues ? distributionRows.map((slice) => slice.value) : [1],
              backgroundColor: distributionHasValues ? distributionRows.map((slice) => slice.color) : ['#cbd5e1'],
              borderColor: '#ffffff',
              borderWidth: 2,
            },
          ],
        },
        options: {
          responsive: true,
          maintainAspectRatio: false,
          plugins: {
            legend: {
              position: 'bottom',
            },
            tooltip: {
              callbacks: {
                label: (context) => {
                  const value = Number(context.raw ?? 0);
                  return `${context.label}: ${value}`;
                },
              },
            },
          },
        },
      }),
    );
  }

  private destroyReportDetailCharts(): void {
    for (const chart of this.reportChartInstances.values()) {
      chart.destroy();
    }

    this.reportChartInstances.clear();
  }

  private getReportChartImageData(canvasId: string): string | null {
    const canvas = document.getElementById(canvasId) as HTMLCanvasElement | null;
    return canvas ? canvas.toDataURL('image/png', 1) : null;
  }

  private async generateReportSignature(payload: string): Promise<string> {
    const encodedPayload = new TextEncoder().encode(payload);
    const digest = await crypto.subtle.digest('SHA-256', encodedPayload);
    return Array.from(new Uint8Array(digest))
      .slice(0, 12)
      .map((value) => value.toString(16).padStart(2, '0'))
      .join('')
      .toUpperCase();
  }

  private decorateReportPdfPages(document: any, title: string, timestamp: string, signature: string): void {
    const totalPages = document.getNumberOfPages();
    const pageWidth = document.internal.pageSize.getWidth();
    const pageHeight = document.internal.pageSize.getHeight();

    for (let pageNumber = 1; pageNumber <= totalPages; pageNumber += 1) {
      document.setPage(pageNumber);
      document.setFontSize(9);
      document.text(this.title, 14, 8);
      document.text(title, pageWidth - 14, 8, { align: 'right' });
      document.text(`Generato: ${timestamp}`, 14, pageHeight - 8);
      document.text(`Firma: ${signature}`, 14, pageHeight - 4);
      document.text(`Pagina ${pageNumber}/${totalPages}`, pageWidth - 14, pageHeight - 4, { align: 'right' });
    }
  }

  private isIphoneOrIpad(): boolean {
    const userAgent = navigator.userAgent.toLowerCase();
    return /iphone|ipad|ipod/.test(userAgent) || (userAgent.includes('macintosh') && 'ontouchend' in document);
  }

  private ensureSelectedStaffMember(): void {
    const activeStaffMembers = this.activeStaffMembers();
    const currentSelectedId = this.saleForm.staffMemberId;

    if (activeStaffMembers.some((member) => member.id === currentSelectedId)) {
      return;
    }

    this.saleForm.staffMemberId = activeStaffMembers[0]?.id ?? '';
  }

  private ensureSelectedAttendanceStaffMember(): void {
    const activeEmployeeStaffMembers = this.activeEmployeeStaffMembers();

    if (!activeEmployeeStaffMembers.some((staffMember) => staffMember.id === this.attendanceForm.staffMemberId)) {
      this.attendanceForm.staffMemberId = activeEmployeeStaffMembers[0]?.id ?? '';
    }

    if (!this.employeeStaffMembers().some((staffMember) => staffMember.id === this.attendanceFilter.staffMemberId)) {
      this.attendanceFilter.staffMemberId =
        this.employeeStaffMembers()[0]?.id ?? '';
    }

    this.selectedAttendanceStaffMemberId.set(this.attendanceFilter.staffMemberId);

    this.onAttendanceStaffChange();
  }

  private getSelectedAttendanceStaffMember(): StaffMember | undefined {
    return this.employeeStaffMembers().find((staffMember) => staffMember.id === this.attendanceForm.staffMemberId);
  }

  private getAttendanceStaffMemberById(staffMemberId: string): StaffMember | undefined {
    return this.staffMembers().find((staffMember) => staffMember.id === staffMemberId);
  }

  private getWeekdayKeyFromDate(isoDate: string): WeekdayKey {
    const [yearValue, monthValue, dayValue] = isoDate.split('-');
    const year = Number.parseInt(yearValue, 10);
    const month = Number.parseInt(monthValue, 10);
    const day = Number.parseInt(dayValue, 10);
    const date = new Date(year, month - 1, day);
    const weekdayMap: WeekdayKey[] = ['domenica', 'lunedi', 'martedi', 'mercoledi', 'giovedi', 'venerdi', 'sabato'];
    return weekdayMap[date.getDay()];
  }

  private getPlannedShiftForDate(staffMember: StaffMember, isoDate: string) {
    const weekdayKey = this.getWeekdayKeyFromDate(isoDate);

    if (this.isCompanyClosureDay(weekdayKey) || this.isNationalHolidayDate(isoDate)) {
      return {
        isWorking: false,
        hours: 0,
      };
    }

    return staffMember.weeklySchedule[weekdayKey];
  }

  private buildMonthlyAttendanceEntries(staffMemberId: string): EffectiveAttendanceEntry[] {
    const { startDate, endDate } = this.getMonthDateRange(this.attendanceFilter.year, this.attendanceFilter.month);
    return this.buildAttendanceEntriesForRange(staffMemberId, startDate, endDate);
  }

  private buildYearlyAttendanceEntries(staffMemberId: string): EffectiveAttendanceEntry[] {
    const startDate = `${this.attendanceFilter.year}-01-01`;
    const endDate = `${this.attendanceFilter.year}-12-31`;
    return this.buildAttendanceEntriesForRange(staffMemberId, startDate, endDate);
  }

  private buildAttendanceEntriesForRange(
    staffMemberId: string,
    startDate: string,
    endDate: string,
  ): EffectiveAttendanceEntry[] {
    const staffMember = this.getAttendanceStaffMemberById(staffMemberId);

    if (!staffMember) {
      return [];
    }

    const explicitEntries = this.attendanceEntries()
      .filter((entry) => entry.staffMemberId === staffMemberId)
      .filter((entry) => entry.entryDate >= startDate && entry.entryDate <= endDate)
      .map((entry) => ({ ...entry, isAutoGenerated: false as const }));
    const explicitEntryMap = new Map(explicitEntries.map((entry) => [entry.entryDate, entry]));
    const employeeStartDate = staffMember.createdAt.slice(0, 10);
    const effectiveEntries: EffectiveAttendanceEntry[] = [];
    const targetDates = this.getDateRange(startDate, endDate);

    for (const isoDate of targetDates) {
      const explicitEntry = explicitEntryMap.get(isoDate);

      if (explicitEntry) {
        effectiveEntries.push(explicitEntry);
        continue;
      }

      if (isoDate < employeeStartDate) {
        continue;
      }

      if (isoDate > this.today()) {
        continue;
      }

      const plannedShift = this.getPlannedShiftForDate(staffMember, isoDate);

      if (!plannedShift.isWorking) {
        continue;
      }

      effectiveEntries.push({
        id: `auto-${staffMemberId}-${isoDate}`,
        staffMemberId,
        entryDate: isoDate,
        entryType: 'lavoro',
        workedHours: plannedShift.hours,
        notes: 'Turno previsto',
        createdAt: isoDate,
        isAutoGenerated: true,
      });
    }

    return effectiveEntries.sort((left, right) => right.entryDate.localeCompare(left.entryDate));
  }

  private buildAttendanceSummary(entries: EffectiveAttendanceEntry[]): AttendanceSummary {
    return entries.reduce(
      (summary, entry) => {
        summary.totalWorkedHours += entry.workedHours;

        if (entry.entryType === 'lavoro') {
          summary.workDays += 1;
        }

        if (entry.entryType === 'festivo') {
          summary.holidayDays += 1;
        }

        if (entry.entryType === 'ferie' && !this.isHolidayDate(entry.entryDate)) {
          summary.vacationDays += 1;
        }

        if (entry.entryType === 'permesso') {
          summary.permitDays += 1;
        }

        if (entry.entryType === 'malattia') {
          summary.sickDays += 1;
        }

        return summary;
      },
      {
        totalWorkedHours: 0,
        workDays: 0,
        holidayDays: 0,
        vacationDays: 0,
        permitDays: 0,
        sickDays: 0,
      },
    );
  }

  private getDateRange(startDate: string, endDate: string): string[] {
    const dates: string[] = [];
    const cursor = new Date(startDate);
    const finalDate = new Date(endDate);

    while (cursor <= finalDate) {
      dates.push(this.toInputDate(cursor));
      cursor.setDate(cursor.getDate() + 1);
    }

    return dates;
  }

  private getAttendanceTargetDates(entryType: AttendanceType, startDate: string, endDate: string): string[] {
    const baseDates =
      entryType === 'ferie' || entryType === 'malattia'
        ? this.getDateRange(startDate, endDate)
        : [startDate];

    if (entryType !== 'ferie') {
      return baseDates;
    }

    return baseDates.filter((isoDate) => !this.isHolidayDate(isoDate));
  }

  private async createAttendanceEntriesForDates(targetDates: string[], normalizedHours: number): Promise<AttendanceEntry[]> {
    const createdEntries: AttendanceEntry[] = [];

    for (const targetDate of targetDates) {
      const createdEntry = await this.storeService.createAttendanceEntry({
        staffMemberId: this.attendanceForm.staffMemberId,
        entryDate: targetDate,
        entryType: this.attendanceForm.entryType,
        workedHours:
          this.attendanceForm.entryType === 'permesso'
            ? normalizedHours
            : this.attendanceForm.entryType === 'lavoro'
              ? normalizedHours
              : 0,
        notes: this.attendanceForm.notes,
      });
      createdEntries.push(createdEntry);
    }

    return createdEntries;
  }

  private findConflictingExplicitEntry(targetDates: string[], excludedEntryIds: string[]): AttendanceEntry | undefined {
    return this.attendanceEntries().find(
      (entry) =>
        entry.staffMemberId === this.attendanceForm.staffMemberId &&
        targetDates.includes(entry.entryDate) &&
        !excludedEntryIds.includes(entry.id),
    );
  }

  private getAttendanceEditEntries(entry: AttendanceEntry): AttendanceEntry[] {
    if (entry.entryType !== 'ferie' && entry.entryType !== 'malattia') {
      return [entry];
    }

    const candidateEntries = this.attendanceEntries()
      .filter(
        (candidateEntry) =>
          candidateEntry.staffMemberId === entry.staffMemberId &&
          candidateEntry.entryType === entry.entryType &&
          candidateEntry.notes === entry.notes,
      )
      .sort((left, right) => left.entryDate.localeCompare(right.entryDate));
    const entriesByDate = new Map(candidateEntries.map((candidateEntry) => [candidateEntry.entryDate, candidateEntry]));
    const groupedEntries: AttendanceEntry[] = [entry];
    let previousDate = entry.entryDate;
    let nextDate = entry.entryDate;

    while (true) {
      const candidateDate = this.getNearestWorkingDate(previousDate, -1);

      if (!candidateDate) {
        break;
      }

      const candidateEntry = entriesByDate.get(candidateDate);

      if (!candidateEntry) {
        break;
      }

      groupedEntries.unshift(candidateEntry);
      previousDate = candidateDate;
    }

    while (true) {
      const candidateDate = this.getNearestWorkingDate(nextDate, 1);

      if (!candidateDate) {
        break;
      }

      const candidateEntry = entriesByDate.get(candidateDate);

      if (!candidateEntry) {
        break;
      }

      groupedEntries.push(candidateEntry);
      nextDate = candidateDate;
    }

    return groupedEntries;
  }

  private getNearestWorkingDate(startDate: string, direction: -1 | 1): string | null {
    let cursorDate = startDate;

    for (let attempt = 0; attempt < 370; attempt += 1) {
      cursorDate = this.shiftIsoDate(cursorDate, direction);

      if (!this.isHolidayDate(cursorDate)) {
        return cursorDate;
      }
    }

    return null;
  }

  private shiftIsoDate(isoDate: string, dayOffset: number): string {
    const shiftedDate = new Date(isoDate);
    shiftedDate.setDate(shiftedDate.getDate() + dayOffset);
    return this.toInputDate(shiftedDate);
  }

  private isCompanyClosureDate(isoDate: string): boolean {
    return this.isCompanyClosureDay(this.getWeekdayKeyFromDate(isoDate));
  }

  private isNationalHolidayDate(isoDate: string): boolean {
    const fixedNationalHolidays = new Set([
      '01-01',
      '01-06',
      '04-25',
      '05-01',
      '06-02',
      '08-15',
      '11-01',
      '12-08',
      '12-25',
      '12-26',
    ]);
    const monthDay = isoDate.slice(5, 10);

    if (fixedNationalHolidays.has(monthDay)) {
      return true;
    }

    const easterMonday = this.getEasterMondayIsoDate(Number.parseInt(isoDate.slice(0, 4), 10));
    return isoDate === easterMonday;
  }

  private getEasterMondayIsoDate(year: number): string {
    const easterDate = this.getEasterDate(year);
    easterDate.setDate(easterDate.getDate() + 1);
    return this.toInputDate(easterDate);
  }

  private getEasterDate(year: number): Date {
    const century = Math.floor(year / 100);
    const yearInCentury = year % 100;
    const leapCenturyAdjust = Math.floor(century / 4);
    const centuryRemainder = century % 4;
    const correction = Math.floor((century + 8) / 25);
    const moonCorrection = Math.floor((century - correction + 1) / 3);
    const epact = (19 * (year % 19) + century - leapCenturyAdjust - moonCorrection + 15) % 30;
    const yearQuarter = Math.floor(yearInCentury / 4);
    const yearRemainder = yearInCentury % 4;
    const weekdayCorrection = (32 + 2 * centuryRemainder + 2 * yearQuarter - epact - yearRemainder) % 7;
    const monthAdjust = Math.floor((year % 19 + 11 * epact + 22 * weekdayCorrection) / 451);
    const month = Math.floor((epact + weekdayCorrection - 7 * monthAdjust + 114) / 31);
    const day = ((epact + weekdayCorrection - 7 * monthAdjust + 114) % 31) + 1;
    return new Date(year, month - 1, day);
  }

  private getWeeklyScheduleValidationError(weeklySchedule: WeeklyShiftTemplate): string | null {
    for (const weekday of this.weekdayOptions) {
      const dayConfig = weeklySchedule[weekday.key];

      if (this.isCompanyClosureDay(weekday.key) && dayConfig.isWorking) {
        return `Non puoi impostare ${weekday.label} come lavorativo se l'azienda e chiusa.`;
      }

      if (dayConfig.isWorking && dayConfig.hours <= 0) {
        return `Inserisci ore maggiori di zero per ${weekday.label}.`;
      }

      if (!dayConfig.isWorking && dayConfig.hours !== 0) {
        return `Per ${weekday.label} non lavorativo le ore devono essere zero.`;
      }
    }

    return null;
  }

  private normalizeWeeklyScheduleForm(weeklySchedule: WeeklyShiftTemplate): WeeklyShiftTemplate {
    const normalizedSchedule = this.cloneWeeklySchedule(weeklySchedule);

    for (const weekday of this.weekdayOptions) {
      if (this.isCompanyClosureDay(weekday.key)) {
        normalizedSchedule[weekday.key] = {
          isWorking: false,
          hours: 0,
        };
        continue;
      }

      normalizedSchedule[weekday.key] = {
        isWorking: normalizedSchedule[weekday.key].isWorking,
        hours: normalizedSchedule[weekday.key].isWorking
          ? this.normalizeAmount(normalizedSchedule[weekday.key].hours)
          : 0,
      };
    }

    return normalizedSchedule;
  }

  private cloneWeeklySchedule(weeklySchedule: WeeklyShiftTemplate): WeeklyShiftTemplate {
    return {
      lunedi: { ...weeklySchedule.lunedi },
      martedi: { ...weeklySchedule.martedi },
      mercoledi: { ...weeklySchedule.mercoledi },
      giovedi: { ...weeklySchedule.giovedi },
      venerdi: { ...weeklySchedule.venerdi },
      sabato: { ...weeklySchedule.sabato },
      domenica: { ...weeklySchedule.domenica },
    };
  }

  protected getAttendanceTypeLabel(entryType: AttendanceType): string {
    return this.attendanceTypeOptions.find((option) => option.value === entryType)?.label ?? 'Presenza';
  }

  protected isHolidayDate(isoDate: string): boolean {
    return this.isCompanyClosureDate(isoDate) || this.isNationalHolidayDate(isoDate);
  }

  protected getAttendanceDayCardClass(isoDate: string, entry: AttendanceEntry | null): string {
    if (entry) {
      return `attendance-day attendance-day-${entry.entryType}`;
    }

    if (this.isHolidayDate(isoDate)) {
      return 'attendance-day attendance-day-festivo';
    }

    return 'attendance-day attendance-day-empty';
  }

  protected getAttendanceDayListCopy(day: AttendanceCalendarDay): string {
    if (day.entry) {
      if (day.entry.entryType === 'ferie') {
        return 'Ferie';
      }

      if (day.entry.entryType === 'malattia') {
        return 'Malattia';
      }

      if (day.entry.entryType === 'festivo') {
        return 'Chiuso';
      }

      return `${this.getAttendanceTypeLabel(day.entry.entryType)} · ${this.formatCompactHours(day.entry.workedHours)}h`;
    }

    if (day.isCompanyClosed) {
      return 'Chiuso';
    }

    if (day.isNationalHoliday) {
      return 'Festivo nazionale';
    }

    if (day.plannedShift?.isWorking) {
      return `${this.formatCompactHours(day.plannedShift.hours)}h previste`;
    }

    return 'Non lavorativo';
  }

  private resetStaffForm(): void {
    this.editingStaffMemberId.set(null);
    this.staffForm.fullName = '';
    this.staffForm.role = 'dipendente';
    this.staffForm.defaultDailyHours = 8;
    this.staffForm.weeklySchedule = createWeeklyShiftTemplate(8);
  }

  private resetAttendanceForm(): void {
    this.editingAttendanceEntryId.set(null);
    this.editingAttendanceEntryIds.set([]);
    this.attendanceForm.entryDate = this.today();
    this.attendanceForm.endDate = this.today();
    this.attendanceForm.entryType = 'lavoro';
    this.attendanceForm.notes = '';
    this.onAttendanceStaffChange();
  }

  private setFeedback(type: 'success' | 'error' | 'info', message: string): void {
    if (this.feedbackTimeoutId) {
      window.clearTimeout(this.feedbackTimeoutId);
    }

    this.feedback.set({ type, message });
    this.feedbackTimeoutId = window.setTimeout(() => {
      this.feedback.set(null);
      this.feedbackTimeoutId = null;
    }, 2800);
  }

  private formatCompactHours(hours: number): string {
    return Number.isInteger(hours) ? String(hours) : String(hours).replace('.', ',');
  }

  private getErrorMessage(error: unknown, fallbackMessage: string): string {
    if (error instanceof Error && error.message) {
      return error.message;
    }

    return fallbackMessage;
  }
}
